all:
	strc --library Tester.str DataStruct.str lqHouse.str WienerHopfSolution.str qr.str matlabFunctions.str AdaptiveBeamform.str ABsteeringMatrix.str Stap.str DopplerFilter.str Cfar.str Detection.str Pulse.str DFT.str -i 1

