package streamittest;

import java.io.*;

/**
 * All messages (informational and error) that are generated by the
 * regression tests are passed to this class.
 **/

public class ResultPrinter {
    /** to turn on verbose output **/
    static final boolean VERBOSE = false;
    static final String ERROR_FILE = "regtest_errors.txt";
    
    static FileWriter fout = null;
    
    /**
     * Print the current test being performed.
     **/
    public static void printTest(String testclass,
				 String testname,
				 String message) {
	if (VERBOSE) {
	    System.out.println(testclass + ":" +
			       testname + "-->" +
			       message);
	}
    }

    /**
     * Print an informational message
     **/
    public static void printInfo(String message) {
	if (VERBOSE) {
	    System.out.println(message);
	}
    }

    /**
     * Print an error message.
     **/
    public static void printError(String message) {
	// make the filewriter if necessary
	if (fout == null) {
	    makeFileWriter();
	}
	try {
	    // write to the output file
	    fout.write(message + "\n");
	} catch (Exception e) {
	    System.out.println("Error printing to the error output");
	    e.printStackTrace();
	    throw new RuntimeException();
	}
	if (VERBOSE) {
	    System.out.println(message);
	}
    }

    /**
     * Create a filewriter to write error messages to.
     **/
    public static void makeFileWriter() {
	try {
	    // create the filewriter, append mode
	    fout = new FileWriter(ERROR_FILE);
	} catch (Exception e) {
	    System.out.println("Error -- failed to create FileWriter for regression test output");
	    e.printStackTrace();
	}
    }	

    /**
     * flushes any output to disk.
     **/
    public static void flushFileWriter() {
	try {
	    if (fout != null) {
		// for disk flush
		fout.flush();
	    }
	} catch (Exception e) {
	    System.out.println("Error -- failed to flush filewriter");
	    e.printStackTrace();
	}
    }

}
	
