// Generated by msggen from AntlrMessages.msg
package at.dms.compiler.tools.antlr.compiler;

import at.dms.util.MessageDescription;

public interface AntlrMessages extends at.dms.compiler.CompilerMessages {
}
