// $ANTLR 1.5A: "Kjc.g" -> "KjcParser.java"$
 package at.dms.kjc; 
import at.dms.compiler.tools.antlr.runtime.*;

  import java.util.Vector;

  import at.dms.compiler.CWarning;
  import at.dms.compiler.Compiler;
  import at.dms.compiler.JavaStyleComment;
  import at.dms.compiler.JavadocComment;
  import at.dms.compiler.PositionedError;
  import at.dms.compiler.TokenReference;
  import at.dms.compiler.tools.antlr.extra.InputBuffer;

public class KjcParser extends at.dms.compiler.tools.antlr.extra.Parser
       implements KjcTokenTypes
 {

  public KjcParser(Compiler compiler, InputBuffer buffer) {
    super(compiler, new KjcScanner(compiler, buffer), MAX_LOOKAHEAD);
  }
// Generated by at.dms.compiler.tools.antlr
private static final int MAX_LOOKAHEAD = 2;
{
  tokenNames = _tokenNames;
}
// Generated by at.dms.compiler.tools.antlr

	public final JCompilationUnit  jCompilationUnit(
		
	) throws RecognitionException, TokenStreamException {
		JCompilationUnit self = null;
		
		
		JPackageName			pack;
		CParseCompilationUnitContext	context = CParseCompilationUnitContext.getInstance();
		TokenReference		sourceRef = buildTokenReference();
		
		
		pack=jPackageDeclaration();
		if ( inputState.guessing==0 ) {
			context.setPackage(pack);
		}
		jImportDeclarations(context);
		{
		_loop3:
		do {
			if ((_tokenSet_0.member(LA(1)))) {
				jTypeDefinition(context);
			}
			else {
				break _loop3;
			}
			
		} while (true);
		}
		match(Token.EOF_TYPE);
		if ( inputState.guessing==0 ) {
			
			self = new JCompilationUnit(sourceRef,
							  pack,
							  context.getPackageImports(),
							  context.getClassImports(),
							  context.getTypeDeclarations());
			context.release();
			
		}
		return self;
	}
	
	private final JPackageName  jPackageDeclaration(
		
	) throws RecognitionException, TokenStreamException {
		JPackageName self = JPackageName.UNNAMED;
		
		
		String	name;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_package:
		{
			match(LITERAL_package);
			name=jIdentifier();
			match(SEMI);
			if ( inputState.guessing==0 ) {
				self = new JPackageName(buildTokenReference(), name, getStatementComment());
			}
			break;
		}
		case EOF:
		case LITERAL_abstract:
		case LITERAL_class:
		case LITERAL_final:
		case LITERAL_import:
		case LITERAL_interface:
		case LITERAL_native:
		case LITERAL_private:
		case LITERAL_protected:
		case LITERAL_public:
		case LITERAL_static:
		case LITERAL_strictfp:
		case LITERAL_synchronized:
		case LITERAL_transient:
		case LITERAL_volatile:
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final void jImportDeclarations(
		CParseCompilationUnitContext context
	) throws RecognitionException, TokenStreamException {
		
		
		jAutomaticImports(context);
		{
		_loop8:
		do {
			if ((LA(1)==LITERAL_import)) {
				jImportDeclaration(context);
			}
			else {
				break _loop8;
			}
			
		} while (true);
		}
	}
	
	private final void jTypeDefinition(
		CParseCompilationUnitContext context
	) throws RecognitionException, TokenStreamException {
		
		
		int			mods = 0;
		JTypeDeclaration	decl = null;
		TokenReference	sourceRef = buildTokenReference();
		
		
		switch ( LA(1)) {
		case LITERAL_abstract:
		case LITERAL_class:
		case LITERAL_final:
		case LITERAL_interface:
		case LITERAL_native:
		case LITERAL_private:
		case LITERAL_protected:
		case LITERAL_public:
		case LITERAL_static:
		case LITERAL_strictfp:
		case LITERAL_synchronized:
		case LITERAL_transient:
		case LITERAL_volatile:
		{
			mods=jModifiers();
			{
			switch ( LA(1)) {
			case LITERAL_class:
			{
				decl=jClassDefinition(mods);
				break;
			}
			case LITERAL_interface:
			{
				decl=jInterfaceDefinition(mods);
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			if ( inputState.guessing==0 ) {
				context.addTypeDeclaration(decl);
			}
			break;
		}
		case SEMI:
		{
			match(SEMI);
			if ( inputState.guessing==0 ) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.STRAY_SEMICOLON, null));
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
	}
	
	private final String  jIdentifier(
		
	) throws RecognitionException, TokenStreamException {
		String self = null;
		
		Token  i = null;
		Token  j = null;
		
		StringBuffer buffer = null;
		
		
		i = LT(1);
		match(IDENT);
		{
		_loop31:
		do {
			if ((LA(1)==DOT)) {
				match(DOT);
				j = LT(1);
				match(IDENT);
				if ( inputState.guessing==0 ) {
					(buffer == null ? (buffer = new StringBuffer(i.getText())) : buffer).append('/').append(j.getText());
				}
			}
			else {
				break _loop31;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			self = buffer == null ? i.getText() : buffer.toString();
		}
		return self;
	}
	
	private final void jAutomaticImports(
		CParseCompilationUnitContext context
	) throws RecognitionException, TokenStreamException {
		
		
		if ( inputState.guessing==0 ) {
			
			context.addPackageImport(new JPackageImport(TokenReference.NO_REF, "java/lang", null));
			
		}
	}
	
	private final void jImportDeclaration(
		CParseCompilationUnitContext context
	) throws RecognitionException, TokenStreamException {
		
		Token  i = null;
		Token  j = null;
		
		StringBuffer	buffer = null;
		boolean	star = false;
		String	name = null;
		
		
		match(LITERAL_import);
		i = LT(1);
		match(IDENT);
		{
		_loop12:
		do {
			if ((LA(1)==DOT) && (LA(2)==IDENT)) {
				match(DOT);
				j = LT(1);
				match(IDENT);
				if ( inputState.guessing==0 ) {
					(buffer == null ? (buffer = new StringBuffer(i.getText())) : buffer).append('/').append(j.getText());
				}
			}
			else {
				break _loop12;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			name = buffer == null ? i.getText() : buffer.toString();
		}
		{
		switch ( LA(1)) {
		case DOT:
		{
			match(DOT);
			match(STAR);
			if ( inputState.guessing==0 ) {
				star = true;
			}
			break;
		}
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(SEMI);
		if ( inputState.guessing==0 ) {
			
			if (star) {
				context.addPackageImport(new JPackageImport(buildTokenReference(), name, getStatementComment()));
			} else {
				context.addClassImport(new JClassImport(buildTokenReference(), name, getStatementComment()));
			}
			
		}
	}
	
	private final int  jModifiers(
		
	) throws RecognitionException, TokenStreamException {
		int self = 0;
		
		
		int		mod;
		
		
		{
		_loop19:
		do {
			if ((_tokenSet_1.member(LA(1)))) {
				mod=jModifier();
				if ( inputState.guessing==0 ) {
					
						if ((mod & self) != 0) {
						  reportTrouble(new PositionedError(buildTokenReference(),
										    KjcMessages.DUPLICATE_MODIFIER,
										    CModifier.getName(mod)));
						}
					
						if (!CModifier.checkOrder(self, mod)) {
						  reportTrouble(new CWarning(buildTokenReference(),
									     KjcMessages.MODIFIER_ORDER,
									     CModifier.getName(mod)));
						}
						self |= mod;
					
				}
			}
			else {
				break _loop19;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			
			//!!! 010428 move to JXxxDeclaration
			if (CModifier.getSubsetSize(self,
							  at.dms.kjc.Constants.ACC_PUBLIC
							  | at.dms.kjc.Constants.ACC_PROTECTED
							  | at.dms.kjc.Constants.ACC_PRIVATE) > 1) {
				reportTrouble(new PositionedError(buildTokenReference(),
								  KjcMessages.INCOMPATIBLE_MODIFIERS,
								  CModifier.toString(CModifier.getSubsetOf(self,
													   at.dms.kjc.Constants.ACC_PUBLIC
													   | at.dms.kjc.Constants.ACC_PROTECTED
													   | at.dms.kjc.Constants.ACC_PRIVATE))));
			}
			
		}
		return self;
	}
	
	private final JClassDeclaration  jClassDefinition(
		int modifiers
	) throws RecognitionException, TokenStreamException {
		JClassDeclaration self = null;
		
		Token  ident = null;
		
		CClassType		superClass = null;
		CClassType[]		interfaces = CClassType.EMPTY;
		CParseClassContext	context = CParseClassContext.getInstance();
		TokenReference	sourceRef = buildTokenReference();
		JavadocComment	javadoc = getJavadocComment();
		JavaStyleComment[]	comments = getStatementComment();
		
		
		match(LITERAL_class);
		ident = LT(1);
		match(IDENT);
		superClass=jSuperClassClause();
		interfaces=jImplementsClause();
		jClassBlock(context);
		if ( inputState.guessing==0 ) {
			
			self = new JClassDeclaration(sourceRef,
							   modifiers,
							   ident.getText(),
							   superClass,
							   interfaces,
							   context.getFields(),
							   context.getMethods(),
							   context.getInnerClasses(),
							   context.getBody(),
							   javadoc,
							   comments);
			context.release();
			
		}
		return self;
	}
	
	private final JInterfaceDeclaration  jInterfaceDefinition(
		int modifiers
	) throws RecognitionException, TokenStreamException {
		JInterfaceDeclaration self = null;
		
		Token  ident = null;
		
		CClassType[]		interfaces =  CClassType.EMPTY;
		CParseClassContext	context = CParseClassContext.getInstance();
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_interface);
		ident = LT(1);
		match(IDENT);
		interfaces=jInterfaceExtends();
		jClassBlock(context);
		if ( inputState.guessing==0 ) {
			
			self = new JInterfaceDeclaration(sourceRef,
							       modifiers,
							       ident.getText(),
							       interfaces,
							       context.getFields(),
							       context.getMethods(),
							       context.getInnerClasses(),
							       context.getBody(),
							       getJavadocComment(),
							       getStatementComment());
			context.release();
			
		}
		return self;
	}
	
	private final JVariableDeclarationStatement  jLocalVariableDeclaration(
		int modifiers
	) throws RecognitionException, TokenStreamException {
		JVariableDeclarationStatement self = null;
		
		
		CType			type;
		JVariableDefinition[] decl;
		TokenReference	sourceRef = buildTokenReference();
		
		
		type=jTypeSpec();
		decl=jVariableDefinitions(modifiers, type);
		if ( inputState.guessing==0 ) {
			
			self = new JVariableDeclarationStatement(sourceRef,
								      decl,
								      getStatementComment());
			
		}
		return self;
	}
	
	private final CType  jTypeSpec(
		
	) throws RecognitionException, TokenStreamException {
		CType self = null;
		
		
		switch ( LA(1)) {
		case IDENT:
		{
			self=jClassTypeSpec();
			break;
		}
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_short:
		case LITERAL_void:
		{
			self=jBuiltInTypeSpec();
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JVariableDefinition[]  jVariableDefinitions(
		int modifiers, CType type
	) throws RecognitionException, TokenStreamException {
		JVariableDefinition[] self = null;
		
		
		Vector		vars = new Vector();
		JVariableDefinition	decl;
		
		
		decl=jVariableDeclarator(modifiers, type);
		if ( inputState.guessing==0 ) {
			vars.addElement(decl);
		}
		{
		_loop64:
		do {
			if ((LA(1)==COMMA)) {
				match(COMMA);
				decl=jVariableDeclarator(modifiers, type);
				if ( inputState.guessing==0 ) {
					vars.addElement(decl);
				}
			}
			else {
				break _loop64;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			self = (JVariableDefinition[])at.dms.util.Utils.toArray(vars, JVariableDefinition.class);
		}
		return self;
	}
	
	private final int  jModifier(
		
	) throws RecognitionException, TokenStreamException {
		int self = 0;
		
		
		switch ( LA(1)) {
		case LITERAL_public:
		{
			match(LITERAL_public);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_PUBLIC;
			}
			break;
		}
		case LITERAL_protected:
		{
			match(LITERAL_protected);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_PROTECTED;
			}
			break;
		}
		case LITERAL_private:
		{
			match(LITERAL_private);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_PRIVATE;
			}
			break;
		}
		case LITERAL_static:
		{
			match(LITERAL_static);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_STATIC;
			}
			break;
		}
		case LITERAL_abstract:
		{
			match(LITERAL_abstract);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_ABSTRACT;
			}
			break;
		}
		case LITERAL_final:
		{
			match(LITERAL_final);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_FINAL;
			}
			break;
		}
		case LITERAL_native:
		{
			match(LITERAL_native);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_NATIVE;
			}
			break;
		}
		case LITERAL_strictfp:
		{
			match(LITERAL_strictfp);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_STRICT;
			}
			break;
		}
		case LITERAL_synchronized:
		{
			match(LITERAL_synchronized);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_SYNCHRONIZED;
			}
			break;
		}
		case LITERAL_transient:
		{
			match(LITERAL_transient);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_TRANSIENT;
			}
			break;
		}
		case LITERAL_volatile:
		{
			match(LITERAL_volatile);
			if ( inputState.guessing==0 ) {
				self = at.dms.kjc.Constants.ACC_VOLATILE;
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final CType  jClassTypeSpec(
		
	) throws RecognitionException, TokenStreamException {
		CType self = null;
		
		
		String		name = null;
		int			bounds = 0;
		
		
		self=jTypeName();
		{
		_loop23:
		do {
			if ((LA(1)==LBRACK)) {
				match(LBRACK);
				match(RBRACK);
				if ( inputState.guessing==0 ) {
					bounds += 1;
				}
			}
			else {
				break _loop23;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			
			if (bounds > 0) {
				self = new CArrayType(self, bounds);
			}
			
		}
		return self;
	}
	
	private final CType  jBuiltInTypeSpec(
		
	) throws RecognitionException, TokenStreamException {
		CType self = null;
		
		
		int			bounds = 0;
		
		
		self=jBuiltInType();
		{
		_loop26:
		do {
			if ((LA(1)==LBRACK)) {
				match(LBRACK);
				match(RBRACK);
				if ( inputState.guessing==0 ) {
					bounds += 1;
				}
			}
			else {
				break _loop26;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			
			if (bounds > 0) {
				self = new CArrayType(self, bounds);
			}
			
		}
		return self;
	}
	
	private final CClassType  jTypeName(
		
	) throws RecognitionException, TokenStreamException {
		CClassType self = null;
		
		
		String	name;
		
		
		name=jIdentifier();
		if ( inputState.guessing==0 ) {
			self = CClassType.lookup(name);
		}
		return self;
	}
	
	private final CType  jBuiltInType(
		
	) throws RecognitionException, TokenStreamException {
		CType self = null;
		
		
		switch ( LA(1)) {
		case LITERAL_void:
		{
			match(LITERAL_void);
			if ( inputState.guessing==0 ) {
				self = CStdType.Void;
			}
			break;
		}
		case LITERAL_boolean:
		{
			match(LITERAL_boolean);
			if ( inputState.guessing==0 ) {
				self = CStdType.Boolean;
			}
			break;
		}
		case LITERAL_byte:
		{
			match(LITERAL_byte);
			if ( inputState.guessing==0 ) {
				self = CStdType.Byte;
			}
			break;
		}
		case LITERAL_char:
		{
			match(LITERAL_char);
			if ( inputState.guessing==0 ) {
				self = CStdType.Char;
			}
			break;
		}
		case LITERAL_short:
		{
			match(LITERAL_short);
			if ( inputState.guessing==0 ) {
				self = CStdType.Short;
			}
			break;
		}
		case LITERAL_int:
		{
			match(LITERAL_int);
			if ( inputState.guessing==0 ) {
				self = CStdType.Integer;
			}
			break;
		}
		case LITERAL_long:
		{
			match(LITERAL_long);
			if ( inputState.guessing==0 ) {
				self = CStdType.Long;
			}
			break;
		}
		case LITERAL_float:
		{
			match(LITERAL_float);
			if ( inputState.guessing==0 ) {
				self = CStdType.Float;
			}
			break;
		}
		case LITERAL_double:
		{
			match(LITERAL_double);
			if ( inputState.guessing==0 ) {
				self = CStdType.Double;
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final CType  jType(
		
	) throws RecognitionException, TokenStreamException {
		CType type = null;
		
		
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_short:
		case LITERAL_void:
		{
			type=jBuiltInType();
			break;
		}
		case IDENT:
		{
			type=jTypeName();
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return type;
	}
	
	private final CClassType  jSuperClassClause(
		
	) throws RecognitionException, TokenStreamException {
		CClassType self = null;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_extends:
		{
			match(LITERAL_extends);
			self=jTypeName();
			break;
		}
		case LITERAL_implements:
		case LCURLY:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final CClassType[]  jImplementsClause(
		
	) throws RecognitionException, TokenStreamException {
		CClassType[] self = CClassType.EMPTY;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_implements:
		{
			match(LITERAL_implements);
			self=jNameList();
			break;
		}
		case LCURLY:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final void jClassBlock(
		CParseClassContext context
	) throws RecognitionException, TokenStreamException {
		
		
		match(LCURLY);
		{
		_loop39:
		do {
			switch ( LA(1)) {
			case LITERAL_abstract:
			case LITERAL_boolean:
			case LITERAL_byte:
			case LITERAL_char:
			case LITERAL_class:
			case LITERAL_double:
			case LITERAL_final:
			case LITERAL_float:
			case LITERAL_int:
			case LITERAL_interface:
			case LITERAL_long:
			case LITERAL_native:
			case LITERAL_private:
			case LITERAL_protected:
			case LITERAL_public:
			case LITERAL_short:
			case LITERAL_static:
			case LITERAL_strictfp:
			case LITERAL_synchronized:
			case LITERAL_transient:
			case LITERAL_void:
			case LITERAL_volatile:
			case LCURLY:
			case IDENT:
			{
				jMember(context);
				break;
			}
			case SEMI:
			{
				match(SEMI);
				if ( inputState.guessing==0 ) {
					reportTrouble(new CWarning(buildTokenReference(), KjcMessages.STRAY_SEMICOLON, null));
				}
				break;
			}
			default:
			{
				break _loop39;
			}
			}
		} while (true);
		}
		match(RCURLY);
	}
	
	private final CClassType[]  jInterfaceExtends(
		
	) throws RecognitionException, TokenStreamException {
		CClassType[] self = CClassType.EMPTY;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_extends:
		{
			match(LITERAL_extends);
			self=jNameList();
			break;
		}
		case LCURLY:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final void jMember(
		CParseClassContext context
	) throws RecognitionException, TokenStreamException {
		
		
		int				modifiers = 0;
		CType				type;
		JMethodDeclaration		method;
		JTypeDeclaration		decl;
		JVariableDefinition[]		vars;
		JStatement[]			body = null;
		TokenReference		sourceRef = buildTokenReference();
		
		
		if ((_tokenSet_2.member(LA(1))) && (_tokenSet_3.member(LA(2)))) {
			modifiers=jModifiers();
			{
			switch ( LA(1)) {
			case LITERAL_class:
			{
				decl=jClassDefinition(modifiers);
				if ( inputState.guessing==0 ) {
					context.addInnerDeclaration(decl);
				}
				break;
			}
			case LITERAL_interface:
			{
				decl=jInterfaceDefinition(modifiers);
				if ( inputState.guessing==0 ) {
					context.addInnerDeclaration(decl);
				}
				break;
			}
			default:
				if ((LA(1)==IDENT) && (LA(2)==LPAREN)) {
					method=jConstructorDefinition(modifiers);
					if ( inputState.guessing==0 ) {
						context.addMethodDeclaration(method);
					}
				}
				else if ((_tokenSet_4.member(LA(1))) && (_tokenSet_5.member(LA(2)))) {
					type=jTypeSpec();
					{
					if ((LA(1)==IDENT) && (LA(2)==LPAREN)) {
						method=jMethodDefinition(modifiers, type);
						if ( inputState.guessing==0 ) {
							context.addMethodDeclaration(method);
						}
					}
					else if ((LA(1)==IDENT) && (_tokenSet_6.member(LA(2)))) {
						vars=jVariableDefinitions(modifiers, type);
						match(SEMI);
						if ( inputState.guessing==0 ) {
							
								  for (int i = 0; i < vars.length; i++) {
								    context.addFieldDeclaration(new JFieldDeclaration(sourceRef,
														      vars[i],
														      getJavadocComment(),
														      getStatementComment()));
								  }
								
						}
					}
					else {
						throw new NoViableAltException(LT(1), getFilename());
					}
					
					}
				}
			else {
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
		}
		else if ((LA(1)==LITERAL_static) && (LA(2)==LCURLY)) {
			match(LITERAL_static);
			body=jCompoundStatement();
			if ( inputState.guessing==0 ) {
				context.addBlockInitializer(new JClassBlock(sourceRef, true, body));
			}
		}
		else if ((LA(1)==LCURLY)) {
			body=jCompoundStatement();
			if ( inputState.guessing==0 ) {
				context.addBlockInitializer(new JClassBlock(sourceRef, false, body));
			}
		}
		else {
			throw new NoViableAltException(LT(1), getFilename());
		}
		
	}
	
	private final CClassType[]  jNameList(
		
	) throws RecognitionException, TokenStreamException {
		CClassType[] self = null;
		
		
		CClassType	name;
		Vector	container = new Vector();
		
		
		name=jTypeName();
		if ( inputState.guessing==0 ) {
			container.addElement(name);
		}
		{
		_loop207:
		do {
			if ((LA(1)==COMMA)) {
				match(COMMA);
				name=jTypeName();
				if ( inputState.guessing==0 ) {
					container.addElement(name);
				}
			}
			else {
				break _loop207;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			self = (CClassType[])at.dms.util.Utils.toArray(container, CClassType.class);
		}
		return self;
	}
	
	private final JConstructorDeclaration  jConstructorDefinition(
		int modifiers
	) throws RecognitionException, TokenStreamException {
		JConstructorDeclaration self = null;
		
		Token  name = null;
		
		JFormalParameter[]	parameters;
		CClassType[]		throwsList = CClassType.EMPTY;
		JConstructorCall	constructorCall = null;
		Vector		body = new Vector();
		JStatement		stmt;
		TokenReference	sourceRef = buildTokenReference();
		JavadocComment	javadoc = getJavadocComment();
		JavaStyleComment[]	comments = getStatementComment();
		
		
		name = LT(1);
		match(IDENT);
		match(LPAREN);
		parameters=jParameterDeclarationList(JLocalVariable.DES_PARAMETER);
		match(RPAREN);
		{
		switch ( LA(1)) {
		case LITERAL_throws:
		{
			throwsList=jThrowsClause();
			break;
		}
		case LCURLY:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(LCURLY);
		{
		boolean synPredMatched52 = false;
		if (((LA(1)==LITERAL_super||LA(1)==LITERAL_this) && (LA(2)==LPAREN))) {
			int _m52 = mark();
			synPredMatched52 = true;
			inputState.guessing++;
			try {
				{
				{
				switch ( LA(1)) {
				case LITERAL_this:
				{
					match(LITERAL_this);
					break;
				}
				case LITERAL_super:
				{
					match(LITERAL_super);
					break;
				}
				default:
				{
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				match(LPAREN);
				}
			}
			catch (RecognitionException pe) {
				synPredMatched52 = false;
			}
			rewind(_m52);
			inputState.guessing--;
		}
		if ( synPredMatched52 ) {
			constructorCall=jExplicitConstructorInvocation();
		}
		else if ((_tokenSet_7.member(LA(1))) && (_tokenSet_8.member(LA(2)))) {
		}
		else {
			throw new NoViableAltException(LT(1), getFilename());
		}
		
		}
		{
		_loop54:
		do {
			if ((_tokenSet_9.member(LA(1)))) {
				stmt=jBlockStatement();
				if ( inputState.guessing==0 ) {
					
						if (stmt instanceof JEmptyStatement) {
						  reportTrouble(new CWarning(stmt.getTokenReference(), KjcMessages.STRAY_SEMICOLON, null));
						}
						body.addElement(stmt);
					
				}
			}
			else {
				break _loop54;
			}
			
		} while (true);
		}
		match(RCURLY);
		if ( inputState.guessing==0 ) {
			
			self = new JConstructorDeclaration(sourceRef,
								 modifiers,
								 name.getText(),
								 parameters,
								 throwsList,
								 constructorCall,
								 (JStatement[])at.dms.util.Utils.toArray(body, JStatement.class),
								 javadoc,
								 comments);
			
		}
		return self;
	}
	
	private final JMethodDeclaration  jMethodDefinition(
		int modifiers, CType type
	) throws RecognitionException, TokenStreamException {
		JMethodDeclaration self = null;
		
		Token  name = null;
		
		JFormalParameter[]	parameters;
		int			bounds = 0;
		CClassType[]		throwsList = CClassType.EMPTY;
		JStatement[]		body = null;
		TokenReference	sourceRef = buildTokenReference();
		JavadocComment	javadoc = getJavadocComment();
		JavaStyleComment[]	comments = getStatementComment();
		
		
		name = LT(1);
		match(IDENT);
		match(LPAREN);
		parameters=jParameterDeclarationList(JLocalVariable.DES_PARAMETER);
		match(RPAREN);
		{
		_loop59:
		do {
			if ((LA(1)==LBRACK)) {
				match(LBRACK);
				match(RBRACK);
				if ( inputState.guessing==0 ) {
					bounds += 1;
				}
			}
			else {
				break _loop59;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			
			if (bounds > 0) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.OLD_STYLE_ARRAY_BOUNDS, null));
				type = new CArrayType(type, bounds);
			}
			
		}
		{
		switch ( LA(1)) {
		case LITERAL_throws:
		{
			throwsList=jThrowsClause();
			break;
		}
		case LCURLY:
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		{
		switch ( LA(1)) {
		case LCURLY:
		{
			body=jCompoundStatement();
			break;
		}
		case SEMI:
		{
			match(SEMI);
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		if ( inputState.guessing==0 ) {
			
			self = new JMethodDeclaration(sourceRef,
							    modifiers,
							    type,
							    name.getText(),
							    parameters,
							    throwsList,
							    body == null ? null : new JBlock(sourceRef, body, null),
							    javadoc,
							    comments);
			
		}
		return self;
	}
	
	private final JStatement[]  jCompoundStatement(
		
	) throws RecognitionException, TokenStreamException {
		JStatement[] self = null;
		
		
		Vector		body = new Vector();
		JStatement		stmt;
		
		
		match(LCURLY);
		{
		_loop86:
		do {
			if ((_tokenSet_9.member(LA(1)))) {
				stmt=jBlockStatement();
				if ( inputState.guessing==0 ) {
					
						if (stmt instanceof JEmptyStatement) {
						  reportTrouble(new CWarning(stmt.getTokenReference(), KjcMessages.STRAY_SEMICOLON, null));
						}
						body.addElement(stmt);
					
				}
			}
			else {
				break _loop86;
			}
			
		} while (true);
		}
		match(RCURLY);
		if ( inputState.guessing==0 ) {
			self = (JStatement[])at.dms.util.Utils.toArray(body, JStatement.class);
		}
		return self;
	}
	
	private final JFormalParameter[]  jParameterDeclarationList(
		int desc
	) throws RecognitionException, TokenStreamException {
		JFormalParameter[] self = JFormalParameter.EMPTY;
		
		
		JFormalParameter		elem = null;
		Vector			vect = new Vector();
		
		
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_final:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_short:
		case LITERAL_void:
		case IDENT:
		{
			elem=jParameterDeclaration(desc);
			if ( inputState.guessing==0 ) {
				vect.addElement(elem);
			}
			{
			_loop79:
			do {
				if ((LA(1)==COMMA)) {
					match(COMMA);
					elem=jParameterDeclaration(desc);
					if ( inputState.guessing==0 ) {
						vect.addElement(elem);
					}
				}
				else {
					break _loop79;
				}
				
			} while (true);
			}
			if ( inputState.guessing==0 ) {
				self = (JFormalParameter[])at.dms.util.Utils.toArray(vect, JFormalParameter.class);
			}
			break;
		}
		case RPAREN:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final CClassType[]  jThrowsClause(
		
	) throws RecognitionException, TokenStreamException {
		CClassType[] self;
		
		
		match(LITERAL_throws);
		self=jNameList();
		return self;
	}
	
	private final JConstructorCall  jExplicitConstructorInvocation(
		
	) throws RecognitionException, TokenStreamException {
		JConstructorCall self = null;
		
		
		boolean		functorIsThis = false;
		JExpression[]		args = null;
		JavaStyleComment[]	comments = getStatementComment();
		TokenReference	sourceRef = buildTokenReference();
		
		
		{
		switch ( LA(1)) {
		case LITERAL_this:
		{
			match(LITERAL_this);
			if ( inputState.guessing==0 ) {
				functorIsThis = true;
			}
			break;
		}
		case LITERAL_super:
		{
			match(LITERAL_super);
			if ( inputState.guessing==0 ) {
				functorIsThis = false;
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(LPAREN);
		args=jArgList();
		match(RPAREN);
		match(SEMI);
		if ( inputState.guessing==0 ) {
			self = new JConstructorCall(sourceRef, functorIsThis, args);
		}
		return self;
	}
	
	private final JStatement  jBlockStatement(
		
	) throws RecognitionException, TokenStreamException {
		JStatement self = null;
		
		
		JTypeDeclaration	type;
		int			modifiers;
		
		
		boolean synPredMatched89 = false;
		if (((_tokenSet_10.member(LA(1))) && (_tokenSet_11.member(LA(2))))) {
			int _m89 = mark();
			synPredMatched89 = true;
			inputState.guessing++;
			try {
				{
				jModifiers();
				match(LITERAL_class);
				}
			}
			catch (RecognitionException pe) {
				synPredMatched89 = false;
			}
			rewind(_m89);
			inputState.guessing--;
		}
		if ( synPredMatched89 ) {
			modifiers=jModifiers();
			type=jClassDefinition(modifiers);
			if ( inputState.guessing==0 ) {
				self = new JTypeDeclarationStatement(type.getTokenReference(), type);
			}
		}
		else {
			boolean synPredMatched91 = false;
			if (((_tokenSet_12.member(LA(1))) && (_tokenSet_13.member(LA(2))))) {
				int _m91 = mark();
				synPredMatched91 = true;
				inputState.guessing++;
				try {
					{
					jModifiers();
					jTypeSpec();
					match(IDENT);
					}
				}
				catch (RecognitionException pe) {
					synPredMatched91 = false;
				}
				rewind(_m91);
				inputState.guessing--;
			}
			if ( synPredMatched91 ) {
				modifiers=jModifiers();
				self=jLocalVariableDeclaration(modifiers);
				match(SEMI);
			}
			else if ((_tokenSet_14.member(LA(1))) && (_tokenSet_15.member(LA(2)))) {
				self=jStatement();
			}
			else {
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			return self;
		}
		
	private final JExpression[]  jArgList(
		
	) throws RecognitionException, TokenStreamException {
		JExpression[] self = JExpression.EMPTY;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case DEC:
		case INC:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			self=jExpressionList();
			break;
		}
		case RPAREN:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JVariableDefinition  jVariableDeclarator(
		int modifiers, CType type
	) throws RecognitionException, TokenStreamException {
		JVariableDefinition self = null;
		
		Token  ident = null;
		
		int			bounds = 0;
		JExpression		expr = null;
		TokenReference	sourceRef = buildTokenReference();
		
		
		ident = LT(1);
		match(IDENT);
		{
		_loop67:
		do {
			if ((LA(1)==LBRACK)) {
				match(LBRACK);
				match(RBRACK);
				if ( inputState.guessing==0 ) {
					bounds += 1;
				}
			}
			else {
				break _loop67;
			}
			
		} while (true);
		}
		{
		switch ( LA(1)) {
		case ASSIGN:
		{
			match(ASSIGN);
			expr=jVariableInitializer();
			break;
		}
		case COMMA:
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		if ( inputState.guessing==0 ) {
			
			if (bounds > 0) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.OLD_STYLE_ARRAY_BOUNDS, null));
				type = new CArrayType(type, bounds);
			}
			self = new JVariableDefinition(sourceRef, modifiers, type, ident.getText(), expr);
			
		}
		return self;
	}
	
	private final JExpression  jVariableInitializer(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case DEC:
		case INC:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			self=jExpression();
			break;
		}
		case LCURLY:
		{
			self=jArrayInitializer();
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JExpression  jExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		self=jAssignmentExpression();
		return self;
	}
	
	private final JArrayInitializer  jArrayInitializer(
		
	) throws RecognitionException, TokenStreamException {
		JArrayInitializer self = null;
		
		
		JExpression		expr = null;
		Vector		vect = new Vector();
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LCURLY);
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case DEC:
		case INC:
		case LCURLY:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			expr=jVariableInitializer();
			if ( inputState.guessing==0 ) {
				vect.addElement(expr);
			}
			{
			_loop73:
			do {
				if ((LA(1)==COMMA) && (_tokenSet_16.member(LA(2)))) {
					match(COMMA);
					expr=jVariableInitializer();
					if ( inputState.guessing==0 ) {
						vect.addElement(expr);
					}
				}
				else {
					break _loop73;
				}
				
			} while (true);
			}
			break;
		}
		case COMMA:
		case RCURLY:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		{
		switch ( LA(1)) {
		case COMMA:
		{
			match(COMMA);
			if ( inputState.guessing==0 ) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.STRAY_COMMA, null));
			}
			break;
		}
		case RCURLY:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(RCURLY);
		if ( inputState.guessing==0 ) {
			
			self = new JArrayInitializer(sourceRef,
							   (JExpression[])at.dms.util.Utils.toArray(vect, JExpression.class));
			
		}
		return self;
	}
	
	private final JFormalParameter  jParameterDeclaration(
		int desc
	) throws RecognitionException, TokenStreamException {
		JFormalParameter self = null;
		
		Token  ident = null;
		
		boolean	isFinal = false;
		int		bounds = 0;
		CType		type;
		TokenReference	sourceRef = buildTokenReference();
		
		
		{
		switch ( LA(1)) {
		case LITERAL_final:
		{
			match(LITERAL_final);
			if ( inputState.guessing==0 ) {
				isFinal = true;
			}
			break;
		}
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_short:
		case LITERAL_void:
		case IDENT:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		type=jTypeSpec();
		ident = LT(1);
		match(IDENT);
		{
		_loop83:
		do {
			if ((LA(1)==LBRACK)) {
				match(LBRACK);
				match(RBRACK);
				if ( inputState.guessing==0 ) {
					bounds += 1;
				}
			}
			else {
				break _loop83;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			
			if (bounds > 0) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.OLD_STYLE_ARRAY_BOUNDS, null));
				type = new CArrayType(type, bounds);
			}
			self = new JFormalParameter(sourceRef, desc, type, ident.getText(), isFinal);
			
		}
		return self;
	}
	
	private final JStatement  jStatement(
		
	) throws RecognitionException, TokenStreamException {
		JStatement self = null;
		
		
		JExpression		expr;
		JStatement[]		stmts;
		JavaStyleComment[]	comments = getStatementComment();
		TokenReference	sourceRef = buildTokenReference();
		
		
		switch ( LA(1)) {
		case LCURLY:
		{
			stmts=jCompoundStatement();
			if ( inputState.guessing==0 ) {
				self = new JBlock(sourceRef, stmts, comments);
			}
			break;
		}
		case LITERAL_if:
		{
			self=jIfStatement();
			break;
		}
		case LITERAL_for:
		{
			self=jForStatement();
			break;
		}
		case LITERAL_while:
		{
			self=jWhileStatement();
			break;
		}
		case LITERAL_do:
		{
			self=jDoStatement();
			break;
		}
		case LITERAL_break:
		{
			self=jBreakStatement();
			break;
		}
		case LITERAL_continue:
		{
			self=jContinueStatement();
			break;
		}
		case LITERAL_return:
		{
			self=jReturnStatement();
			break;
		}
		case LITERAL_switch:
		{
			self=jSwitchStatement();
			break;
		}
		case LITERAL_try:
		{
			self=jTryBlock();
			break;
		}
		case LITERAL_throw:
		{
			self=jThrowStatement();
			break;
		}
		case LITERAL_synchronized:
		{
			self=jSynchronizedStatement();
			break;
		}
		case SEMI:
		{
			match(SEMI);
			if ( inputState.guessing==0 ) {
				self = new JEmptyStatement(sourceRef, comments);
			}
			break;
		}
		default:
			if ((_tokenSet_17.member(LA(1))) && (_tokenSet_18.member(LA(2)))) {
				expr=jExpression();
				match(SEMI);
				if ( inputState.guessing==0 ) {
					self = new JExpressionStatement(sourceRef, expr, comments);
				}
			}
			else if ((LA(1)==IDENT) && (LA(2)==COLON)) {
				self=jLabeledStatement();
			}
		else {
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JLabeledStatement  jLabeledStatement(
		
	) throws RecognitionException, TokenStreamException {
		JLabeledStatement self = null;
		
		Token  label = null;
		
		JStatement		stmt;
		TokenReference	sourceRef = buildTokenReference();
		
		
		label = LT(1);
		match(IDENT);
		match(COLON);
		stmt=jStatement();
		if ( inputState.guessing==0 ) {
			
			if (stmt instanceof JEmptyStatement) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.STRAY_SEMICOLON, null));
			}
			self = new JLabeledStatement(sourceRef, label.getText(), stmt, getStatementComment());
			
		}
		return self;
	}
	
	private final JIfStatement  jIfStatement(
		
	) throws RecognitionException, TokenStreamException {
		JIfStatement self = null;
		
		
		JExpression		cond;
		JStatement		thenClause;
		JStatement		elseClause = null;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_if);
		match(LPAREN);
		cond=jExpression();
		match(RPAREN);
		thenClause=jStatement();
		if ( inputState.guessing==0 ) {
			
			// LOOKAHEAD OF 2 FORBIDDEN
			if (LA(1)==LITERAL_else) {
			match(LITERAL_else);
			elseClause = jStatement();
			}
			
		}
		if ( inputState.guessing==0 ) {
			
			if (! (thenClause instanceof JBlock)) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.ENCLOSE_IF_THEN_IN_BLOCK, null));
			}
			if (elseClause != null && !(elseClause instanceof JBlock || elseClause instanceof JIfStatement)) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.ENCLOSE_IF_ELSE_IN_BLOCK, null));
			}
			self = new JIfStatement(sourceRef, cond, thenClause, elseClause, getStatementComment());
			
		}
		return self;
	}
	
	private final JForStatement  jForStatement(
		
	) throws RecognitionException, TokenStreamException {
		JForStatement self = null;
		
		
		JStatement		init;
		JExpression		cond;
		JStatement		iter;
		JStatement		body;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_for);
		match(LPAREN);
		init=jForInit();
		match(SEMI);
		cond=jForCond();
		match(SEMI);
		iter=jForIter();
		match(RPAREN);
		body=jStatement();
		if ( inputState.guessing==0 ) {
			
			if (!(body instanceof JBlock || body instanceof JEmptyStatement)) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.ENCLOSE_LOOP_BODY_IN_BLOCK, null));
			}
			self = new JForStatement(sourceRef, init, cond, iter, body, getStatementComment());
			
		}
		return self;
	}
	
	private final JWhileStatement  jWhileStatement(
		
	) throws RecognitionException, TokenStreamException {
		JWhileStatement self = null;
		
		
		JExpression		cond;
		JStatement		body;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_while);
		match(LPAREN);
		cond=jExpression();
		match(RPAREN);
		body=jStatement();
		if ( inputState.guessing==0 ) {
			
			if (!(body instanceof JBlock || body instanceof JEmptyStatement)) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.ENCLOSE_LOOP_BODY_IN_BLOCK, null));
			}
			self = new JWhileStatement(sourceRef, cond, body, getStatementComment());
			
		}
		return self;
	}
	
	private final JDoStatement  jDoStatement(
		
	) throws RecognitionException, TokenStreamException {
		JDoStatement self = null;
		
		
		JExpression		cond;
		JStatement		body;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_do);
		body=jStatement();
		match(LITERAL_while);
		match(LPAREN);
		cond=jExpression();
		match(RPAREN);
		match(SEMI);
		if ( inputState.guessing==0 ) {
			
			if (! (body instanceof JBlock)) {
				reportTrouble(new CWarning(sourceRef, KjcMessages.ENCLOSE_LOOP_BODY_IN_BLOCK, null));
			}
			self = new JDoStatement(sourceRef, cond, body, getStatementComment());
			
		}
		return self;
	}
	
	private final JBreakStatement  jBreakStatement(
		
	) throws RecognitionException, TokenStreamException {
		JBreakStatement self = null;
		
		Token  label = null;
		
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_break);
		{
		switch ( LA(1)) {
		case IDENT:
		{
			label = LT(1);
			match(IDENT);
			break;
		}
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(SEMI);
		if ( inputState.guessing==0 ) {
			self = new JBreakStatement(sourceRef, label == null ? null : label.getText(), getStatementComment());
		}
		return self;
	}
	
	private final JContinueStatement  jContinueStatement(
		
	) throws RecognitionException, TokenStreamException {
		JContinueStatement self = null;
		
		Token  label = null;
		
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_continue);
		{
		switch ( LA(1)) {
		case IDENT:
		{
			label = LT(1);
			match(IDENT);
			break;
		}
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(SEMI);
		if ( inputState.guessing==0 ) {
			self = new JContinueStatement(sourceRef, label == null ? null : label.getText(), getStatementComment());
		}
		return self;
	}
	
	private final JReturnStatement  jReturnStatement(
		
	) throws RecognitionException, TokenStreamException {
		JReturnStatement self = null;
		
		
		JExpression		expr = null;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_return);
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case DEC:
		case INC:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			expr=jExpression();
			break;
		}
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(SEMI);
		if ( inputState.guessing==0 ) {
			self = new JReturnStatement(sourceRef, expr, getStatementComment());
		}
		return self;
	}
	
	private final JSwitchStatement  jSwitchStatement(
		
	) throws RecognitionException, TokenStreamException {
		JSwitchStatement self = null;
		
		
		JExpression		expr = null;
		Vector		body = null;
		JSwitchGroup		group;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_switch);
		match(LPAREN);
		expr=jExpression();
		match(RPAREN);
		match(LCURLY);
		if ( inputState.guessing==0 ) {
			body = new Vector();
		}
		{
		_loop107:
		do {
			if ((LA(1)==LITERAL_case||LA(1)==LITERAL_default)) {
				group=jCasesGroup();
				if ( inputState.guessing==0 ) {
					body.addElement(group);
				}
			}
			else {
				break _loop107;
			}
			
		} while (true);
		}
		match(RCURLY);
		if ( inputState.guessing==0 ) {
			
			self = new JSwitchStatement(sourceRef,
							  expr,
							  (JSwitchGroup[])at.dms.util.Utils.toArray(body, JSwitchGroup.class),
							  getStatementComment());
			
		}
		return self;
	}
	
	private final JStatement  jTryBlock(
		
	) throws RecognitionException, TokenStreamException {
		JStatement self = null;
		
		
		JBlock		tryClause = null;
		JStatement[]		compound;
		Vector		catchClauses = new Vector();
		JBlock		finallyClause = null;
		JCatchClause		catcher = null;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_try);
		compound=jCompoundStatement();
		if ( inputState.guessing==0 ) {
			tryClause = new JBlock(sourceRef, compound, null);
		}
		{
		_loop126:
		do {
			if ((LA(1)==LITERAL_catch)) {
				catcher=jHandler();
				if ( inputState.guessing==0 ) {
					catchClauses.addElement(catcher);
				}
			}
			else {
				break _loop126;
			}
			
		} while (true);
		}
		{
		switch ( LA(1)) {
		case LITERAL_finally:
		{
			match(LITERAL_finally);
			compound=jCompoundStatement();
			if ( inputState.guessing==0 ) {
				finallyClause = new JBlock(sourceRef, compound, null);
			}
			break;
		}
		case LITERAL_abstract:
		case LITERAL_boolean:
		case LITERAL_break:
		case LITERAL_byte:
		case LITERAL_case:
		case LITERAL_char:
		case LITERAL_class:
		case LITERAL_continue:
		case LITERAL_default:
		case LITERAL_do:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_final:
		case LITERAL_float:
		case LITERAL_for:
		case LITERAL_if:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_native:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_private:
		case LITERAL_protected:
		case LITERAL_public:
		case LITERAL_return:
		case LITERAL_short:
		case LITERAL_static:
		case LITERAL_strictfp:
		case LITERAL_super:
		case LITERAL_switch:
		case LITERAL_synchronized:
		case LITERAL_this:
		case LITERAL_throw:
		case LITERAL_transient:
		case LITERAL_true:
		case LITERAL_try:
		case LITERAL_void:
		case LITERAL_volatile:
		case LITERAL_while:
		case BNOT:
		case DEC:
		case INC:
		case LCURLY:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case RCURLY:
		case SEMI:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		if ( inputState.guessing==0 ) {
			
			if (catchClauses.size() > 0) {
				self = new JTryCatchStatement(sourceRef,
							      tryClause,
							      (JCatchClause[])at.dms.util.Utils.toArray(catchClauses, JCatchClause.class),
							      finallyClause == null ? getStatementComment() : null);
			}
			if (finallyClause != null) {
				// If both catch and finally clauses are present,
				// the try-catch is embedded as try clause into a
				// try-finally statement.
				if (self != null) {
				  tryClause = new JBlock(sourceRef, new JStatement[] {self}, null);
				}
				self = new JTryFinallyStatement(sourceRef, tryClause, finallyClause, getStatementComment());
			}
			
			if (self == null) {
				// try without catch or finally: error
				reportTrouble(new PositionedError(sourceRef, KjcMessages.TRY_NOCATCH, null));
				self = tryClause;
			}
			
		}
		return self;
	}
	
	private final JThrowStatement  jThrowStatement(
		
	) throws RecognitionException, TokenStreamException {
		JThrowStatement self = null;
		
		
		JExpression		expr;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_throw);
		expr=jExpression();
		match(SEMI);
		if ( inputState.guessing==0 ) {
			self = new JThrowStatement(sourceRef, expr, getStatementComment());
		}
		return self;
	}
	
	private final JSynchronizedStatement  jSynchronizedStatement(
		
	) throws RecognitionException, TokenStreamException {
		JSynchronizedStatement self = null;
		
		
		JExpression		expr;
		JStatement[]		body;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_synchronized);
		match(LPAREN);
		expr=jExpression();
		match(RPAREN);
		body=jCompoundStatement();
		if ( inputState.guessing==0 ) {
			
			self = new JSynchronizedStatement(sourceRef,
								expr,
								new JBlock(sourceRef, body, null),
								getStatementComment());
			
		}
		return self;
	}
	
	private final JSwitchGroup  jCasesGroup(
		
	) throws RecognitionException, TokenStreamException {
		JSwitchGroup self = null;
		
		
		Vector		labels = new Vector();
		Vector		stmts = new Vector();
		
		JSwitchLabel		label;
		JStatement		stmt;
		TokenReference	sourceRef = buildTokenReference();
		
		
		{
		int _cnt110=0;
		_loop110:
		do {
			if ((LA(1)==LITERAL_case||LA(1)==LITERAL_default) && (_tokenSet_19.member(LA(2)))) {
				label=jACase();
				if ( inputState.guessing==0 ) {
					labels.addElement(label);
				}
			}
			else {
				if ( _cnt110>=1 ) { break _loop110; } else {throw new NoViableAltException(LT(1), getFilename());}
			}
			
			_cnt110++;
		} while (true);
		}
		{
		_loop112:
		do {
			if ((_tokenSet_9.member(LA(1)))) {
				stmt=jBlockStatement();
				if ( inputState.guessing==0 ) {
					
					if (stmt instanceof JEmptyStatement) {
						reportTrouble(new CWarning(stmt.getTokenReference(), KjcMessages.STRAY_SEMICOLON, null));
					}
					stmts.addElement(stmt);
					
				}
			}
			else {
				break _loop112;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			
			self = new JSwitchGroup(sourceRef,
						      (JSwitchLabel[])at.dms.util.Utils.toArray(labels, JSwitchLabel.class),
						      (JStatement[])at.dms.util.Utils.toArray(stmts, JStatement.class));
			
		}
		return self;
	}
	
	private final JSwitchLabel  jACase(
		
	) throws RecognitionException, TokenStreamException {
		JSwitchLabel self = null;
		
		
		JExpression		expr = null;
		TokenReference	sourceRef = buildTokenReference();
		
		
		{
		switch ( LA(1)) {
		case LITERAL_case:
		{
			match(LITERAL_case);
			expr=jExpression();
			if ( inputState.guessing==0 ) {
				self = new JSwitchLabel(sourceRef, expr);
			}
			break;
		}
		case LITERAL_default:
		{
			match(LITERAL_default);
			if ( inputState.guessing==0 ) {
				self = new JSwitchLabel(sourceRef, null);
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		match(COLON);
		return self;
	}
	
	private final JStatement  jForInit(
		
	) throws RecognitionException, TokenStreamException {
		JStatement self = null;
		
		
		int			modifiers;
		JExpression[]		list;
		
		
		{
		boolean synPredMatched119 = false;
		if (((_tokenSet_12.member(LA(1))) && (_tokenSet_13.member(LA(2))))) {
			int _m119 = mark();
			synPredMatched119 = true;
			inputState.guessing++;
			try {
				{
				jModifiers();
				jTypeSpec();
				match(IDENT);
				}
			}
			catch (RecognitionException pe) {
				synPredMatched119 = false;
			}
			rewind(_m119);
			inputState.guessing--;
		}
		if ( synPredMatched119 ) {
			modifiers=jModifiers();
			self=jLocalVariableDeclaration(modifiers);
		}
		else if ((_tokenSet_17.member(LA(1))) && (_tokenSet_20.member(LA(2)))) {
			list=jExpressionList();
			if ( inputState.guessing==0 ) {
				self = new JExpressionListStatement(buildTokenReference(), list, getStatementComment());
			}
		}
		else if ((LA(1)==SEMI)) {
		}
		else {
			throw new NoViableAltException(LT(1), getFilename());
		}
		
		}
		return self;
	}
	
	private final JExpression  jForCond(
		
	) throws RecognitionException, TokenStreamException {
		JExpression expr = null;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case DEC:
		case INC:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			expr=jExpression();
			break;
		}
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return expr;
	}
	
	private final JExpressionListStatement  jForIter(
		
	) throws RecognitionException, TokenStreamException {
		JExpressionListStatement self = null;
		
		
		JExpression[] list;
		
		
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case DEC:
		case INC:
		case LNOT:
		case LPAREN:
		case MINUS:
		case PLUS:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			list=jExpressionList();
			if ( inputState.guessing==0 ) {
				self = new JExpressionListStatement(buildTokenReference(), list, null);
			}
			break;
		}
		case RPAREN:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JExpression[]  jExpressionList(
		
	) throws RecognitionException, TokenStreamException {
		JExpression[] self = null;
		
		
		JExpression		expr;
		Vector		vect = new Vector();
		
		
		expr=jExpression();
		if ( inputState.guessing==0 ) {
			vect.addElement(expr);
		}
		{
		_loop132:
		do {
			if ((LA(1)==COMMA)) {
				match(COMMA);
				expr=jExpression();
				if ( inputState.guessing==0 ) {
					vect.addElement(expr);
				}
			}
			else {
				break _loop132;
			}
			
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			self = (JExpression[])at.dms.util.Utils.toArray(vect, JExpression.class);
		}
		return self;
	}
	
	private final JCatchClause  jHandler(
		
	) throws RecognitionException, TokenStreamException {
		JCatchClause self = null;
		
		
		JFormalParameter	param;
		JStatement[]		body;
		TokenReference	sourceRef = buildTokenReference();
		
		
		match(LITERAL_catch);
		match(LPAREN);
		param=jParameterDeclaration(JLocalVariable.DES_CATCH_PARAMETER);
		match(RPAREN);
		body=jCompoundStatement();
		if ( inputState.guessing==0 ) {
			
			self = new JCatchClause(sourceRef,
						      param,
						      new JBlock(sourceRef, body, null));
			
		}
		return self;
	}
	
	private final JExpression  jAssignmentExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		int			oper = -1;
		JExpression		right;
		
		
		self=jConditionalExpression();
		{
		switch ( LA(1)) {
		case ASSIGN:
		{
			match(ASSIGN);
			right=jAssignmentExpression();
			if ( inputState.guessing==0 ) {
				self = new JAssignmentExpression(self.getTokenReference(), self, right);
			}
			break;
		}
		case BAND_ASSIGN:
		case BOR_ASSIGN:
		case BSR_ASSIGN:
		case BXOR_ASSIGN:
		case MINUS_ASSIGN:
		case PERCENT_ASSIGN:
		case PLUS_ASSIGN:
		case SLASH_ASSIGN:
		case SL_ASSIGN:
		case SR_ASSIGN:
		case STAR_ASSIGN:
		{
			oper=jCompoundAssignmentOperator();
			right=jAssignmentExpression();
			if ( inputState.guessing==0 ) {
				self = new JCompoundAssignmentExpression(self.getTokenReference(), oper, self, right);
			}
			break;
		}
		case COLON:
		case COMMA:
		case RBRACK:
		case RCURLY:
		case RPAREN:
		case SEMI:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JExpression  jConditionalExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		middle;
		JExpression		right;
		
		
		self=jLogicalOrExpression();
		{
		switch ( LA(1)) {
		case QUESTION:
		{
			match(QUESTION);
			middle=jConditionalExpression();
			match(COLON);
			right=jConditionalExpression();
			if ( inputState.guessing==0 ) {
				self = new JConditionalExpression(self.getTokenReference(), self, middle, right);
			}
			break;
		}
		case ASSIGN:
		case BAND_ASSIGN:
		case BOR_ASSIGN:
		case BSR_ASSIGN:
		case BXOR_ASSIGN:
		case COLON:
		case COMMA:
		case MINUS_ASSIGN:
		case PERCENT_ASSIGN:
		case PLUS_ASSIGN:
		case RBRACK:
		case RCURLY:
		case RPAREN:
		case SEMI:
		case SLASH_ASSIGN:
		case SL_ASSIGN:
		case SR_ASSIGN:
		case STAR_ASSIGN:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final int  jCompoundAssignmentOperator(
		
	) throws RecognitionException, TokenStreamException {
		int self = -1;
		
		
		switch ( LA(1)) {
		case PLUS_ASSIGN:
		{
			match(PLUS_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_PLUS;
			}
			break;
		}
		case MINUS_ASSIGN:
		{
			match(MINUS_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_MINUS;
			}
			break;
		}
		case STAR_ASSIGN:
		{
			match(STAR_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_STAR;
			}
			break;
		}
		case SLASH_ASSIGN:
		{
			match(SLASH_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_SLASH;
			}
			break;
		}
		case PERCENT_ASSIGN:
		{
			match(PERCENT_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_PERCENT;
			}
			break;
		}
		case SR_ASSIGN:
		{
			match(SR_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_SR;
			}
			break;
		}
		case BSR_ASSIGN:
		{
			match(BSR_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_BSR;
			}
			break;
		}
		case SL_ASSIGN:
		{
			match(SL_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_SL;
			}
			break;
		}
		case BAND_ASSIGN:
		{
			match(BAND_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_BAND;
			}
			break;
		}
		case BXOR_ASSIGN:
		{
			match(BXOR_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_BXOR;
			}
			break;
		}
		case BOR_ASSIGN:
		{
			match(BOR_ASSIGN);
			if ( inputState.guessing==0 ) {
				self = Constants.OPE_BOR;
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JExpression  jLogicalOrExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jLogicalAndExpression();
		{
		_loop140:
		do {
			if ((LA(1)==LOR)) {
				match(LOR);
				right=jLogicalAndExpression();
				if ( inputState.guessing==0 ) {
					self = new JConditionalOrExpression(self.getTokenReference(), self, right);
				}
			}
			else {
				break _loop140;
			}
			
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jLogicalAndExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jInclusiveOrExpression();
		{
		_loop143:
		do {
			if ((LA(1)==LAND)) {
				match(LAND);
				right=jInclusiveOrExpression();
				if ( inputState.guessing==0 ) {
					self = new JConditionalAndExpression(self.getTokenReference(), self, right);
				}
			}
			else {
				break _loop143;
			}
			
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jInclusiveOrExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jExclusiveOrExpression();
		{
		_loop146:
		do {
			if ((LA(1)==BOR)) {
				match(BOR);
				right=jExclusiveOrExpression();
				if ( inputState.guessing==0 ) {
					self = new JBitwiseExpression(self.getTokenReference(), Constants.OPE_BOR, self, right);
				}
			}
			else {
				break _loop146;
			}
			
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jExclusiveOrExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jAndExpression();
		{
		_loop149:
		do {
			if ((LA(1)==BXOR)) {
				match(BXOR);
				right=jAndExpression();
				if ( inputState.guessing==0 ) {
					self = new JBitwiseExpression(self.getTokenReference(), Constants.OPE_BXOR, self, right);
				}
			}
			else {
				break _loop149;
			}
			
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jAndExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jEqualityExpression();
		{
		_loop152:
		do {
			if ((LA(1)==BAND)) {
				match(BAND);
				right=jEqualityExpression();
				if ( inputState.guessing==0 ) {
					self = new JBitwiseExpression(self.getTokenReference(), Constants.OPE_BAND, self, right);
				}
			}
			else {
				break _loop152;
			}
			
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jEqualityExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jRelationalExpression();
		{
		_loop155:
		do {
			switch ( LA(1)) {
			case NOT_EQUAL:
			{
				match(NOT_EQUAL);
				right=jRelationalExpression();
				if ( inputState.guessing==0 ) {
					self = new JEqualityExpression(self.getTokenReference(), false, self, right);
				}
				break;
			}
			case EQUAL:
			{
				match(EQUAL);
				right=jRelationalExpression();
				if ( inputState.guessing==0 ) {
					self = new JEqualityExpression(self.getTokenReference(), true, self, right);
				}
				break;
			}
			default:
			{
				break _loop155;
			}
			}
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jRelationalExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		int			operator = -1;
		JExpression		right;
		CType			type;
		
		
		self=jShiftExpression();
		{
		switch ( LA(1)) {
		case ASSIGN:
		case BAND:
		case BAND_ASSIGN:
		case BOR:
		case BOR_ASSIGN:
		case BSR_ASSIGN:
		case BXOR:
		case BXOR_ASSIGN:
		case COLON:
		case COMMA:
		case EQUAL:
		case GE:
		case GT:
		case LAND:
		case LE:
		case LOR:
		case LT:
		case MINUS_ASSIGN:
		case NOT_EQUAL:
		case PERCENT_ASSIGN:
		case PLUS_ASSIGN:
		case QUESTION:
		case RBRACK:
		case RCURLY:
		case RPAREN:
		case SEMI:
		case SLASH_ASSIGN:
		case SL_ASSIGN:
		case SR_ASSIGN:
		case STAR_ASSIGN:
		{
			{
			_loop160:
			do {
				if ((_tokenSet_21.member(LA(1)))) {
					{
					switch ( LA(1)) {
					case LT:
					{
						match(LT);
						if ( inputState.guessing==0 ) {
							operator = Constants.OPE_LT;
						}
						break;
					}
					case GT:
					{
						match(GT);
						if ( inputState.guessing==0 ) {
							operator = Constants.OPE_GT;
						}
						break;
					}
					case LE:
					{
						match(LE);
						if ( inputState.guessing==0 ) {
							operator = Constants.OPE_LE;
						}
						break;
					}
					case GE:
					{
						match(GE);
						if ( inputState.guessing==0 ) {
							operator = Constants.OPE_GE;
						}
						break;
					}
					default:
					{
						throw new NoViableAltException(LT(1), getFilename());
					}
					}
					}
					right=jShiftExpression();
					if ( inputState.guessing==0 ) {
						self = new JRelationalExpression(self.getTokenReference(), operator, self, right);
					}
				}
				else {
					break _loop160;
				}
				
			} while (true);
			}
			break;
		}
		case LITERAL_instanceof:
		{
			match(LITERAL_instanceof);
			type=jTypeSpec();
			if ( inputState.guessing==0 ) {
				self = new JInstanceofExpression(self.getTokenReference(), self, type);
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JExpression  jShiftExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		int			operator = -1;
		JExpression		right;
		
		
		self=jAdditiveExpression();
		{
		_loop164:
		do {
			if ((_tokenSet_22.member(LA(1)))) {
				{
				switch ( LA(1)) {
				case SL:
				{
					match(SL);
					if ( inputState.guessing==0 ) {
						operator = Constants.OPE_SL;
					}
					break;
				}
				case SR:
				{
					match(SR);
					if ( inputState.guessing==0 ) {
						operator = Constants.OPE_SR;
					}
					break;
				}
				case BSR:
				{
					match(BSR);
					if ( inputState.guessing==0 ) {
						operator = Constants.OPE_BSR;
					}
					break;
				}
				default:
				{
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				right=jAdditiveExpression();
				if ( inputState.guessing==0 ) {
					self = new JShiftExpression(self.getTokenReference(), operator, self, right);
				}
			}
			else {
				break _loop164;
			}
			
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jAdditiveExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jMultiplicativeExpression();
		{
		_loop167:
		do {
			switch ( LA(1)) {
			case PLUS:
			{
				match(PLUS);
				right=jMultiplicativeExpression();
				if ( inputState.guessing==0 ) {
					self = new JAddExpression(self.getTokenReference(), self, right);
				}
				break;
			}
			case MINUS:
			{
				match(MINUS);
				right=jMultiplicativeExpression();
				if ( inputState.guessing==0 ) {
					self = new JMinusExpression(self.getTokenReference(), self, right);
				}
				break;
			}
			default:
			{
				break _loop167;
			}
			}
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jMultiplicativeExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		right;
		
		
		self=jUnaryExpression();
		{
		_loop170:
		do {
			switch ( LA(1)) {
			case STAR:
			{
				match(STAR);
				right=jUnaryExpression();
				if ( inputState.guessing==0 ) {
					self = new JMultExpression(self.getTokenReference(), self, right);
				}
				break;
			}
			case SLASH:
			{
				match(SLASH);
				right=jUnaryExpression();
				if ( inputState.guessing==0 ) {
					self = new JDivideExpression(self.getTokenReference(), self, right);
				}
				break;
			}
			case PERCENT:
			{
				match(PERCENT);
				right=jUnaryExpression();
				if ( inputState.guessing==0 ) {
					self = new JModuloExpression(self.getTokenReference(), self, right);
				}
				break;
			}
			default:
			{
				break _loop170;
			}
			}
		} while (true);
		}
		return self;
	}
	
	private final JExpression  jUnaryExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		TokenReference	sourceRef = buildTokenReference();
		
		
		switch ( LA(1)) {
		case INC:
		{
			match(INC);
			self=jUnaryExpression();
			if ( inputState.guessing==0 ) {
				self = new JPrefixExpression(sourceRef, Constants.OPE_PREINC, self);
			}
			break;
		}
		case DEC:
		{
			match(DEC);
			self=jUnaryExpression();
			if ( inputState.guessing==0 ) {
				self = new JPrefixExpression(sourceRef, Constants.OPE_PREDEC, self);
			}
			break;
		}
		case MINUS:
		{
			match(MINUS);
			self=jUnaryExpression();
			if ( inputState.guessing==0 ) {
				self = new JUnaryMinusExpression(sourceRef, self);
			}
			break;
		}
		case PLUS:
		{
			match(PLUS);
			self=jUnaryExpression();
			if ( inputState.guessing==0 ) {
				self = new JUnaryPlusExpression(sourceRef, self);
			}
			break;
		}
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case BNOT:
		case LNOT:
		case LPAREN:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			self=jUnaryExpressionNotPlusMinus();
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JExpression  jUnaryExpressionNotPlusMinus(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		JExpression		expr;
		CType			dest;
		TokenReference	sourceRef = buildTokenReference();
		
		
		switch ( LA(1)) {
		case BNOT:
		{
			match(BNOT);
			self=jUnaryExpression();
			if ( inputState.guessing==0 ) {
				self = new JBitwiseComplementExpression(sourceRef, self);
			}
			break;
		}
		case LNOT:
		{
			match(LNOT);
			self=jUnaryExpression();
			if ( inputState.guessing==0 ) {
				self = new JLogicalComplementExpression(sourceRef, self);
			}
			break;
		}
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_false:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_new:
		case LITERAL_null:
		case LITERAL_short:
		case LITERAL_super:
		case LITERAL_this:
		case LITERAL_true:
		case LITERAL_void:
		case LPAREN:
		case CHARACTER_LITERAL:
		case IDENT:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			{
			if ((LA(1)==LPAREN) && (_tokenSet_23.member(LA(2)))) {
				match(LPAREN);
				dest=jBuiltInTypeSpec();
				match(RPAREN);
				expr=jUnaryExpression();
				if ( inputState.guessing==0 ) {
					self = new JCastExpression(sourceRef, expr, dest);
				}
			}
			else {
				boolean synPredMatched175 = false;
				if (((LA(1)==LPAREN) && (LA(2)==IDENT))) {
					int _m175 = mark();
					synPredMatched175 = true;
					inputState.guessing++;
					try {
						{
						match(LPAREN);
						jClassTypeSpec();
						match(RPAREN);
						jUnaryExpressionNotPlusMinus();
						}
					}
					catch (RecognitionException pe) {
						synPredMatched175 = false;
					}
					rewind(_m175);
					inputState.guessing--;
				}
				if ( synPredMatched175 ) {
					match(LPAREN);
					dest=jClassTypeSpec();
					match(RPAREN);
					expr=jUnaryExpressionNotPlusMinus();
					if ( inputState.guessing==0 ) {
						self = new JCastExpression(sourceRef, expr, dest);
					}
				}
				else if ((_tokenSet_24.member(LA(1))) && (_tokenSet_25.member(LA(2)))) {
					self=jPostfixExpression();
				}
				else {
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			return self;
		}
		
	private final JExpression  jPostfixExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		Token  ident = null;
		
		int			bounds = 0;
		JExpression		expr;
		JExpression[]		args = null;
		CType			type;
		TokenReference	sourceRef = buildTokenReference();
		
		
		self=jPrimaryExpression();
		{
		_loop181:
		do {
			switch ( LA(1)) {
			case DOT:
			{
				match(DOT);
				{
				switch ( LA(1)) {
				case IDENT:
				{
					ident = LT(1);
					match(IDENT);
					if ( inputState.guessing==0 ) {
						self = new JNameExpression(sourceRef, self, ident.getText());
					}
					break;
				}
				case LITERAL_this:
				{
					match(LITERAL_this);
					if ( inputState.guessing==0 ) {
						self = new JThisExpression(sourceRef, self);
					}
					break;
				}
				case LITERAL_class:
				{
					match(LITERAL_class);
					if ( inputState.guessing==0 ) {
						self = new JClassExpression(sourceRef, self, 0);
					}
					break;
				}
				case LITERAL_new:
				{
					self=jQualifiedNewExpression(self);
					break;
				}
				default:
				{
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				break;
			}
			case LPAREN:
			{
				match(LPAREN);
				args=jArgList();
				match(RPAREN);
				if ( inputState.guessing==0 ) {
					
						if (! (self instanceof JNameExpression)) {
						  reportTrouble(new PositionedError(sourceRef, KjcMessages.INVALID_METHOD_NAME, null));
						} else {
						  self = new JMethodCallExpression(sourceRef,
										   ((JNameExpression)self).getPrefix(),
										   ((JNameExpression)self).getName(),
										   args);
						}
					
				}
				break;
			}
			default:
				if ((LA(1)==LBRACK) && (LA(2)==RBRACK)) {
					{
					int _cnt180=0;
					_loop180:
					do {
						if ((LA(1)==LBRACK)) {
							match(LBRACK);
							match(RBRACK);
							if ( inputState.guessing==0 ) {
								bounds++;
							}
						}
						else {
							if ( _cnt180>=1 ) { break _loop180; } else {throw new NoViableAltException(LT(1), getFilename());}
						}
						
						_cnt180++;
					} while (true);
					}
					match(DOT);
					match(LITERAL_class);
					if ( inputState.guessing==0 ) {
						self = new JClassExpression(sourceRef, self, bounds);
					}
				}
				else if ((LA(1)==LBRACK) && (_tokenSet_17.member(LA(2)))) {
					match(LBRACK);
					expr=jExpression();
					match(RBRACK);
					if ( inputState.guessing==0 ) {
						self = new JArrayAccessExpression(sourceRef, self, expr);
					}
				}
			else {
				break _loop181;
			}
			}
		} while (true);
		}
		{
		switch ( LA(1)) {
		case INC:
		{
			match(INC);
			if ( inputState.guessing==0 ) {
				self = new JPostfixExpression(sourceRef, Constants.OPE_POSTINC, self);
			}
			break;
		}
		case DEC:
		{
			match(DEC);
			if ( inputState.guessing==0 ) {
				self = new JPostfixExpression(sourceRef, Constants.OPE_POSTDEC, self);
			}
			break;
		}
		case LITERAL_instanceof:
		case ASSIGN:
		case BAND:
		case BAND_ASSIGN:
		case BOR:
		case BOR_ASSIGN:
		case BSR:
		case BSR_ASSIGN:
		case BXOR:
		case BXOR_ASSIGN:
		case COLON:
		case COMMA:
		case EQUAL:
		case GE:
		case GT:
		case LAND:
		case LE:
		case LOR:
		case LT:
		case MINUS:
		case MINUS_ASSIGN:
		case NOT_EQUAL:
		case PERCENT:
		case PERCENT_ASSIGN:
		case PLUS:
		case PLUS_ASSIGN:
		case QUESTION:
		case RBRACK:
		case RCURLY:
		case RPAREN:
		case SEMI:
		case SL:
		case SLASH:
		case SLASH_ASSIGN:
		case SL_ASSIGN:
		case SR:
		case SR_ASSIGN:
		case STAR:
		case STAR_ASSIGN:
		{
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JExpression  jPrimaryExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		Token  ident = null;
		
		int			bounds = 0;
		CType			type;
		TokenReference	sourceRef = buildTokenReference();
		
		
		switch ( LA(1)) {
		case IDENT:
		{
			ident = LT(1);
			match(IDENT);
			if ( inputState.guessing==0 ) {
				self = new JNameExpression(sourceRef, ident.getText());
			}
			break;
		}
		case LITERAL_new:
		{
			self=jUnqualifiedNewExpression();
			break;
		}
		case CHARACTER_LITERAL:
		case INTEGER_LITERAL:
		case REAL_LITERAL:
		case STRING_LITERAL:
		{
			self=jLiteral();
			break;
		}
		case LITERAL_super:
		{
			match(LITERAL_super);
			if ( inputState.guessing==0 ) {
				self = new JSuperExpression(sourceRef);
			}
			break;
		}
		case LITERAL_true:
		{
			match(LITERAL_true);
			if ( inputState.guessing==0 ) {
				self = new JBooleanLiteral(sourceRef, true);
			}
			break;
		}
		case LITERAL_false:
		{
			match(LITERAL_false);
			if ( inputState.guessing==0 ) {
				self = new JBooleanLiteral(sourceRef, false);
			}
			break;
		}
		case LITERAL_this:
		{
			match(LITERAL_this);
			if ( inputState.guessing==0 ) {
				self = new JThisExpression(sourceRef);
			}
			break;
		}
		case LITERAL_null:
		{
			match(LITERAL_null);
			if ( inputState.guessing==0 ) {
				self = new JNullLiteral(sourceRef);
			}
			break;
		}
		case LPAREN:
		{
			match(LPAREN);
			self=jAssignmentExpression();
			match(RPAREN);
			if ( inputState.guessing==0 ) {
				self = new JParenthesedExpression(sourceRef, self);
			}
			break;
		}
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_short:
		case LITERAL_void:
		{
			type=jBuiltInType();
			{
			_loop185:
			do {
				if ((LA(1)==LBRACK)) {
					match(LBRACK);
					match(RBRACK);
					if ( inputState.guessing==0 ) {
						bounds++;
					}
				}
				else {
					break _loop185;
				}
				
			} while (true);
			}
			match(DOT);
			match(LITERAL_class);
			if ( inputState.guessing==0 ) {
				self = new JClassExpression(buildTokenReference(), type, bounds);
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JExpression  jQualifiedNewExpression(
		JExpression prefix
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		Token  ident = null;
		
		CType				type;
		JExpression[]			args;
		JArrayInitializer		init = null;
		JClassDeclaration		decl = null;
		CParseClassContext		context = null;
		TokenReference		sourceRef = buildTokenReference();
		
		
		match(LITERAL_new);
		ident = LT(1);
		match(IDENT);
		match(LPAREN);
		args=jArgList();
		match(RPAREN);
		{
		switch ( LA(1)) {
		case LCURLY:
		{
			if ( inputState.guessing==0 ) {
				context = CParseClassContext.getInstance();
			}
			jClassBlock(context);
			if ( inputState.guessing==0 ) {
				
					decl = new JClassDeclaration(sourceRef,
								     at.dms.kjc.Constants.ACC_FINAL, // JLS 15.9.5
								     ident.getText(),
								     null,
								     CClassType.EMPTY,
								     context.getFields(),
								     context.getMethods(),
								     context.getInnerClasses(),
								     context.getBody(),
								     getJavadocComment(),
								     getStatementComment());
					context.release();
				
			}
			if ( inputState.guessing==0 ) {
				self = new JQualifiedAnonymousCreation(sourceRef, prefix, ident.getText(), args, decl);
			}
			break;
		}
		case LITERAL_instanceof:
		case ASSIGN:
		case BAND:
		case BAND_ASSIGN:
		case BOR:
		case BOR_ASSIGN:
		case BSR:
		case BSR_ASSIGN:
		case BXOR:
		case BXOR_ASSIGN:
		case COLON:
		case COMMA:
		case DEC:
		case DOT:
		case EQUAL:
		case GE:
		case GT:
		case INC:
		case LAND:
		case LBRACK:
		case LE:
		case LOR:
		case LPAREN:
		case LT:
		case MINUS:
		case MINUS_ASSIGN:
		case NOT_EQUAL:
		case PERCENT:
		case PERCENT_ASSIGN:
		case PLUS:
		case PLUS_ASSIGN:
		case QUESTION:
		case RBRACK:
		case RCURLY:
		case RPAREN:
		case SEMI:
		case SL:
		case SLASH:
		case SLASH_ASSIGN:
		case SL_ASSIGN:
		case SR:
		case SR_ASSIGN:
		case STAR:
		case STAR_ASSIGN:
		{
			if ( inputState.guessing==0 ) {
				self = new JQualifiedInstanceCreation(sourceRef, prefix, ident.getText(), args);
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JExpression  jUnqualifiedNewExpression(
		
	) throws RecognitionException, TokenStreamException {
		JExpression self = null;
		
		
		CType				type;
		JExpression[]			args;
		JArrayInitializer		init = null;
		JClassDeclaration		decl = null;
		CParseClassContext		context = null;
		TokenReference		sourceRef = buildTokenReference();
		
		
		match(LITERAL_new);
		{
		switch ( LA(1)) {
		case LITERAL_boolean:
		case LITERAL_byte:
		case LITERAL_char:
		case LITERAL_double:
		case LITERAL_float:
		case LITERAL_int:
		case LITERAL_long:
		case LITERAL_short:
		case LITERAL_void:
		{
			type=jBuiltInType();
			args=jNewArrayDeclarator();
			{
			switch ( LA(1)) {
			case LCURLY:
			{
				init=jArrayInitializer();
				break;
			}
			case LITERAL_instanceof:
			case ASSIGN:
			case BAND:
			case BAND_ASSIGN:
			case BOR:
			case BOR_ASSIGN:
			case BSR:
			case BSR_ASSIGN:
			case BXOR:
			case BXOR_ASSIGN:
			case COLON:
			case COMMA:
			case DEC:
			case DOT:
			case EQUAL:
			case GE:
			case GT:
			case INC:
			case LAND:
			case LBRACK:
			case LE:
			case LOR:
			case LPAREN:
			case LT:
			case MINUS:
			case MINUS_ASSIGN:
			case NOT_EQUAL:
			case PERCENT:
			case PERCENT_ASSIGN:
			case PLUS:
			case PLUS_ASSIGN:
			case QUESTION:
			case RBRACK:
			case RCURLY:
			case RPAREN:
			case SEMI:
			case SL:
			case SLASH:
			case SLASH_ASSIGN:
			case SL_ASSIGN:
			case SR:
			case SR_ASSIGN:
			case STAR:
			case STAR_ASSIGN:
			{
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			if ( inputState.guessing==0 ) {
				self = new JNewArrayExpression(sourceRef, type, args, init);
			}
			break;
		}
		case IDENT:
		{
			type=jTypeName();
			{
			switch ( LA(1)) {
			case LBRACK:
			{
				args=jNewArrayDeclarator();
				{
				switch ( LA(1)) {
				case LCURLY:
				{
					init=jArrayInitializer();
					break;
				}
				case LITERAL_instanceof:
				case ASSIGN:
				case BAND:
				case BAND_ASSIGN:
				case BOR:
				case BOR_ASSIGN:
				case BSR:
				case BSR_ASSIGN:
				case BXOR:
				case BXOR_ASSIGN:
				case COLON:
				case COMMA:
				case DEC:
				case DOT:
				case EQUAL:
				case GE:
				case GT:
				case INC:
				case LAND:
				case LBRACK:
				case LE:
				case LOR:
				case LPAREN:
				case LT:
				case MINUS:
				case MINUS_ASSIGN:
				case NOT_EQUAL:
				case PERCENT:
				case PERCENT_ASSIGN:
				case PLUS:
				case PLUS_ASSIGN:
				case QUESTION:
				case RBRACK:
				case RCURLY:
				case RPAREN:
				case SEMI:
				case SL:
				case SLASH:
				case SLASH_ASSIGN:
				case SL_ASSIGN:
				case SR:
				case SR_ASSIGN:
				case STAR:
				case STAR_ASSIGN:
				{
					break;
				}
				default:
				{
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				if ( inputState.guessing==0 ) {
					self = new JNewArrayExpression(sourceRef, type, args, init);
				}
				break;
			}
			case LPAREN:
			{
				match(LPAREN);
				args=jArgList();
				match(RPAREN);
				{
				switch ( LA(1)) {
				case LCURLY:
				{
					if ( inputState.guessing==0 ) {
						context = CParseClassContext.getInstance();
					}
					jClassBlock(context);
					if ( inputState.guessing==0 ) {
						
							    decl = new JClassDeclaration(sourceRef,
											 at.dms.kjc.Constants.ACC_FINAL, // JLS 15.9.5
											 ((CClassType)type).getQualifiedName(),
											 null,
											 CClassType.EMPTY,
											 context.getFields(),
											 context.getMethods(),
											 context.getInnerClasses(),
											 context.getBody(),
											 getJavadocComment(),
											 getStatementComment());
							    context.release();
							
					}
					if ( inputState.guessing==0 ) {
						self = new JUnqualifiedAnonymousCreation(sourceRef, (CClassType)type, args, decl);
					}
					break;
				}
				case LITERAL_instanceof:
				case ASSIGN:
				case BAND:
				case BAND_ASSIGN:
				case BOR:
				case BOR_ASSIGN:
				case BSR:
				case BSR_ASSIGN:
				case BXOR:
				case BXOR_ASSIGN:
				case COLON:
				case COMMA:
				case DEC:
				case DOT:
				case EQUAL:
				case GE:
				case GT:
				case INC:
				case LAND:
				case LBRACK:
				case LE:
				case LOR:
				case LPAREN:
				case LT:
				case MINUS:
				case MINUS_ASSIGN:
				case NOT_EQUAL:
				case PERCENT:
				case PERCENT_ASSIGN:
				case PLUS:
				case PLUS_ASSIGN:
				case QUESTION:
				case RBRACK:
				case RCURLY:
				case RPAREN:
				case SEMI:
				case SL:
				case SLASH:
				case SLASH_ASSIGN:
				case SL_ASSIGN:
				case SR:
				case SR_ASSIGN:
				case STAR:
				case STAR_ASSIGN:
				{
					if ( inputState.guessing==0 ) {
						self = new JUnqualifiedInstanceCreation(sourceRef, (CClassType)type, args);
					}
					break;
				}
				default:
				{
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		}
		return self;
	}
	
	private final JLiteral  jLiteral(
		
	) throws RecognitionException, TokenStreamException {
		JLiteral self = null;
		
		
		switch ( LA(1)) {
		case INTEGER_LITERAL:
		{
			self=jIntegerLiteral();
			break;
		}
		case CHARACTER_LITERAL:
		{
			self=jCharLiteral();
			break;
		}
		case STRING_LITERAL:
		{
			self=jStringLiteral();
			break;
		}
		case REAL_LITERAL:
		{
			self=jRealLiteral();
			break;
		}
		default:
		{
			throw new NoViableAltException(LT(1), getFilename());
		}
		}
		return self;
	}
	
	private final JExpression[]  jNewArrayDeclarator(
		
	) throws RecognitionException, TokenStreamException {
		JExpression[] self = null;
		
		
		Vector		container = new Vector();
		JExpression		exp = null;
		
		
		{
		int _cnt199=0;
		_loop199:
		do {
			if ((LA(1)==LBRACK) && (_tokenSet_26.member(LA(2)))) {
				match(LBRACK);
				{
				switch ( LA(1)) {
				case LITERAL_boolean:
				case LITERAL_byte:
				case LITERAL_char:
				case LITERAL_double:
				case LITERAL_false:
				case LITERAL_float:
				case LITERAL_int:
				case LITERAL_long:
				case LITERAL_new:
				case LITERAL_null:
				case LITERAL_short:
				case LITERAL_super:
				case LITERAL_this:
				case LITERAL_true:
				case LITERAL_void:
				case BNOT:
				case DEC:
				case INC:
				case LNOT:
				case LPAREN:
				case MINUS:
				case PLUS:
				case CHARACTER_LITERAL:
				case IDENT:
				case INTEGER_LITERAL:
				case REAL_LITERAL:
				case STRING_LITERAL:
				{
					exp=jExpression();
					break;
				}
				case RBRACK:
				{
					break;
				}
				default:
				{
					throw new NoViableAltException(LT(1), getFilename());
				}
				}
				}
				match(RBRACK);
				if ( inputState.guessing==0 ) {
					container.addElement(exp); exp = null;
				}
			}
			else {
				if ( _cnt199>=1 ) { break _loop199; } else {throw new NoViableAltException(LT(1), getFilename());}
			}
			
			_cnt199++;
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			self = (JExpression[])at.dms.util.Utils.toArray(container, JExpression.class);
		}
		return self;
	}
	
	private final JLiteral  jIntegerLiteral(
		
	) throws RecognitionException, TokenStreamException {
		JLiteral self = null;
		
		Token  i = null;
		
		i = LT(1);
		match(INTEGER_LITERAL);
		if ( inputState.guessing==0 ) {
			
			try {
				self = JLiteral.parseInteger(buildTokenReference(), i.getText());
			} catch (PositionedError e) {
				reportTrouble(e);
				// allow parsing to continue
				self = new JIntLiteral(TokenReference.NO_REF, 0);
			}
			
		}
		return self;
	}
	
	private final JLiteral  jCharLiteral(
		
	) throws RecognitionException, TokenStreamException {
		JLiteral self = null;
		
		Token  c = null;
		
		c = LT(1);
		match(CHARACTER_LITERAL);
		if ( inputState.guessing==0 ) {
			
			try {
				self = new JCharLiteral(buildTokenReference(), c.getText());
			} catch (PositionedError e) {
				reportTrouble(e);
				// allow parsing to continue
				self = new JCharLiteral(TokenReference.NO_REF, '\0');
			}
			
		}
		return self;
	}
	
	private final JLiteral  jStringLiteral(
		
	) throws RecognitionException, TokenStreamException {
		JLiteral self = null;
		
		Token  s = null;
		
		s = LT(1);
		match(STRING_LITERAL);
		if ( inputState.guessing==0 ) {
			self = new JStringLiteral(buildTokenReference(), s.getText());
		}
		return self;
	}
	
	private final JLiteral  jRealLiteral(
		
	) throws RecognitionException, TokenStreamException {
		JLiteral self = null;
		
		Token  r = null;
		
		r = LT(1);
		match(REAL_LITERAL);
		if ( inputState.guessing==0 ) {
			
			try {
				self = JLiteral.parseReal(buildTokenReference(), r.getText());
			} catch (PositionedError e) {
				reportTrouble(e);
				// allow parsing to continue
				self = new JFloatLiteral(TokenReference.NO_REF, 0f);
			}
			
		}
		return self;
	}
	
	
	public static final String[] _tokenNames = {
		"<0>",
		"EOF",
		"<2>",
		"NULL_TREE_LOOKAHEAD",
		"\"abstract\"",
		"\"boolean\"",
		"\"break\"",
		"\"byte\"",
		"\"case\"",
		"\"catch\"",
		"\"char\"",
		"\"class\"",
		"\"const\"",
		"\"continue\"",
		"\"default\"",
		"\"do\"",
		"\"double\"",
		"\"else\"",
		"\"extends\"",
		"\"false\"",
		"\"final\"",
		"\"finally\"",
		"\"float\"",
		"\"for\"",
		"\"goto\"",
		"\"if\"",
		"\"implements\"",
		"\"import\"",
		"\"instanceof\"",
		"\"int\"",
		"\"interface\"",
		"\"long\"",
		"\"native\"",
		"\"new\"",
		"\"null\"",
		"\"package\"",
		"\"private\"",
		"\"protected\"",
		"\"public\"",
		"\"return\"",
		"\"short\"",
		"\"static\"",
		"\"strictfp\"",
		"\"super\"",
		"\"switch\"",
		"\"synchronized\"",
		"\"this\"",
		"\"throw\"",
		"\"throws\"",
		"\"transient\"",
		"\"true\"",
		"\"try\"",
		"\"void\"",
		"\"volatile\"",
		"\"while\"",
		"=",
		"&",
		"&=",
		"~",
		"|",
		"|=",
		">>>",
		">>>=",
		"^",
		"^=",
		":",
		",",
		"--",
		".",
		"==",
		">=",
		">",
		"++",
		"&&",
		"[",
		"{",
		"<=",
		"!",
		"||",
		"(",
		"<",
		"-",
		"-=",
		"!=",
		"%",
		"%=",
		"+",
		"+=",
		"?",
		"]",
		"}",
		")",
		";",
		"<<",
		"/",
		"/=",
		"<<=",
		">>",
		">>=",
		"*",
		"*=",
		"a character literal (inside simple quote)",
		"an identifier",
		"an integer literal",
		"a real literal",
		"a string literal (inside double quote)"
	};
	
	private static final long[] _tokenSet_0_data_ = { 9612417056114704L, 268435456L, 0L, 0L };
	public static final BitSet _tokenSet_0 = new BitSet(_tokenSet_0_data_);
	private static final long[] _tokenSet_1_data_ = { 9612415982370832L, 0L };
	public static final BitSet _tokenSet_1 = new BitSet(_tokenSet_1_data_);
	private static final long[] _tokenSet_2_data_ = { 14117118883728560L, 274877906944L, 0L, 0L };
	public static final BitSet _tokenSet_2 = new BitSet(_tokenSet_2_data_);
	private static final long[] _tokenSet_3_data_ = { 14117118883728560L, 274877940752L, 0L, 0L };
	public static final BitSet _tokenSet_3 = new BitSet(_tokenSet_3_data_);
	private static final long[] _tokenSet_4_data_ = { 4504701827613856L, 274877906944L, 0L, 0L };
	public static final BitSet _tokenSet_4 = new BitSet(_tokenSet_4_data_);
	private static final long[] _tokenSet_5_data_ = { 0L, 274877907984L, 0L, 0L };
	public static final BitSet _tokenSet_5 = new BitSet(_tokenSet_5_data_);
	private static final long[] _tokenSet_6_data_ = { 36028797018963968L, 268436484L, 0L, 0L };
	public static final BitSet _tokenSet_6 = new BitSet(_tokenSet_6_data_);
	private static final long[] _tokenSet_7_data_ = { 323977662271433968L, 4260947470600L, 0L, 0L };
	public static final BitSet _tokenSet_7 = new BitSet(_tokenSet_7_data_);
	private static final long[] _tokenSet_8_data_ = { -281509557064464L, 4397878738939L, 0L, 0L };
	public static final BitSet _tokenSet_8 = new BitSet(_tokenSet_8_data_);
	private static final long[] _tokenSet_9_data_ = { 323977662271433968L, 4260880361736L, 0L, 0L };
	public static final BitSet _tokenSet_9 = new BitSet(_tokenSet_9_data_);
	private static final long[] _tokenSet_10_data_ = { 9612415982372880L, 0L };
	public static final BitSet _tokenSet_10 = new BitSet(_tokenSet_10_data_);
	private static final long[] _tokenSet_11_data_ = { 9612415982372880L, 274877906944L, 0L, 0L };
	public static final BitSet _tokenSet_11 = new BitSet(_tokenSet_11_data_);
	private static final long[] _tokenSet_12_data_ = { 14117117809984688L, 274877906944L, 0L, 0L };
	public static final BitSet _tokenSet_12 = new BitSet(_tokenSet_12_data_);
	private static final long[] _tokenSet_13_data_ = { 14117117809984688L, 274877907984L, 0L, 0L };
	public static final BitSet _tokenSet_13 = new BitSet(_tokenSet_13_data_);
	private static final long[] _tokenSet_14_data_ = { 314400430661149920L, 4260880361736L, 0L, 0L };
	public static final BitSet _tokenSet_14 = new BitSet(_tokenSet_14_data_);
	private static final long[] _tokenSet_15_data_ = { -281510630789648L, 4397878738939L, 0L, 0L };
	public static final BitSet _tokenSet_15 = new BitSet(_tokenSet_15_data_);
	private static final long[] _tokenSet_16_data_ = { 293940168493696160L, 4260611926280L, 0L, 0L };
	public static final BitSet _tokenSet_16 = new BitSet(_tokenSet_16_data_);
	private static final long[] _tokenSet_17_data_ = { 293940168493696160L, 4260611924232L, 0L, 0L };
	public static final BitSet _tokenSet_17 = new BitSet(_tokenSet_17_data_);
	private static final long[] _tokenSet_18_data_ = { -30319004408544096L, 4397811628025L, 0L, 0L };
	public static final BitSet _tokenSet_18 = new BitSet(_tokenSet_18_data_);
	private static final long[] _tokenSet_19_data_ = { 293940168493696160L, 4260611924234L, 0L, 0L };
	public static final BitSet _tokenSet_19 = new BitSet(_tokenSet_19_data_);
	private static final long[] _tokenSet_20_data_ = { -30319004408544096L, 4397811628029L, 0L, 0L };
	public static final BitSet _tokenSet_20 = new BitSet(_tokenSet_20_data_);
	private static final long[] _tokenSet_21_data_ = { 0L, 69824L, 0L, 0L };
	public static final BitSet _tokenSet_21 = new BitSet(_tokenSet_21_data_);
	private static final long[] _tokenSet_22_data_ = { 2305843009213693952L, 9126805504L, 0L, 0L };
	public static final BitSet _tokenSet_22 = new BitSet(_tokenSet_22_data_);
	private static final long[] _tokenSet_23_data_ = { 4504701827613856L, 0L };
	public static final BitSet _tokenSet_23 = new BitSet(_tokenSet_23_data_);
	private static final long[] _tokenSet_24_data_ = { 5709792341984416L, 4260607590400L, 0L, 0L };
	public static final BitSet _tokenSet_24 = new BitSet(_tokenSet_24_data_);
	private static final long[] _tokenSet_25_data_ = { -30319004408544096L, 4398046509055L, 0L, 0L };
	public static final BitSet _tokenSet_25 = new BitSet(_tokenSet_25_data_);
	private static final long[] _tokenSet_26_data_ = { 293940168493696160L, 4260645478664L, 0L, 0L };
	public static final BitSet _tokenSet_26 = new BitSet(_tokenSet_26_data_);
	
	}
