// Generated from Kjc.t
package at.dms.kjc;

public interface KjcTokenTypes {
  int	EOF = 1;
  int	NULL_TREE_LOOKAHEAD = 3;
  int	LITERAL_abstract = 4;
  int	LITERAL_boolean = 5;
  int	LITERAL_break = 6;
  int	LITERAL_byte = 7;
  int	LITERAL_case = 8;
  int	LITERAL_catch = 9;
  int	LITERAL_char = 10;
  int	LITERAL_class = 11;
  int	LITERAL_const = 12;
  int	LITERAL_continue = 13;
  int	LITERAL_default = 14;
  int	LITERAL_do = 15;
  int	LITERAL_double = 16;
  int	LITERAL_else = 17;
  int	LITERAL_extends = 18;
  int	LITERAL_false = 19;
  int	LITERAL_final = 20;
  int	LITERAL_finally = 21;
  int	LITERAL_float = 22;
  int	LITERAL_for = 23;
  int	LITERAL_goto = 24;
  int	LITERAL_if = 25;
  int	LITERAL_implements = 26;
  int	LITERAL_import = 27;
  int	LITERAL_instanceof = 28;
  int	LITERAL_int = 29;
  int	LITERAL_interface = 30;
  int	LITERAL_long = 31;
  int	LITERAL_native = 32;
  int	LITERAL_new = 33;
  int	LITERAL_null = 34;
  int	LITERAL_package = 35;
  int	LITERAL_private = 36;
  int	LITERAL_protected = 37;
  int	LITERAL_public = 38;
  int	LITERAL_return = 39;
  int	LITERAL_short = 40;
  int	LITERAL_static = 41;
  int	LITERAL_strictfp = 42;
  int	LITERAL_super = 43;
  int	LITERAL_switch = 44;
  int	LITERAL_synchronized = 45;
  int	LITERAL_this = 46;
  int	LITERAL_throw = 47;
  int	LITERAL_throws = 48;
  int	LITERAL_transient = 49;
  int	LITERAL_true = 50;
  int	LITERAL_try = 51;
  int	LITERAL_void = 52;
  int	LITERAL_volatile = 53;
  int	LITERAL_while = 54;
  int	ASSIGN = 55;
  int	BAND = 56;
  int	BAND_ASSIGN = 57;
  int	BNOT = 58;
  int	BOR = 59;
  int	BOR_ASSIGN = 60;
  int	BSR = 61;
  int	BSR_ASSIGN = 62;
  int	BXOR = 63;
  int	BXOR_ASSIGN = 64;
  int	COLON = 65;
  int	COMMA = 66;
  int	DEC = 67;
  int	DOT = 68;
  int	EQUAL = 69;
  int	GE = 70;
  int	GT = 71;
  int	INC = 72;
  int	LAND = 73;
  int	LBRACK = 74;
  int	LCURLY = 75;
  int	LE = 76;
  int	LNOT = 77;
  int	LOR = 78;
  int	LPAREN = 79;
  int	LT = 80;
  int	MINUS = 81;
  int	MINUS_ASSIGN = 82;
  int	NOT_EQUAL = 83;
  int	PERCENT = 84;
  int	PERCENT_ASSIGN = 85;
  int	PLUS = 86;
  int	PLUS_ASSIGN = 87;
  int	QUESTION = 88;
  int	RBRACK = 89;
  int	RCURLY = 90;
  int	RPAREN = 91;
  int	SEMI = 92;
  int	SL = 93;
  int	SLASH = 94;
  int	SLASH_ASSIGN = 95;
  int	SL_ASSIGN = 96;
  int	SR = 97;
  int	SR_ASSIGN = 98;
  int	STAR = 99;
  int	STAR_ASSIGN = 100;
  int	CHARACTER_LITERAL = 101;
  int	IDENT = 102;
  int	INTEGER_LITERAL = 103;
  int	REAL_LITERAL = 104;
  int	STRING_LITERAL = 105;
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_abstract = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_abstract, "abstract");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_boolean = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_boolean, "boolean");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_break = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_break, "break");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_byte = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_byte, "byte");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_case = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_case, "case");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_catch = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_catch, "catch");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_char = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_char, "char");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_class = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_class, "class");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_const = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_const, "const");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_continue = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_continue, "continue");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_default = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_default, "default");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_do = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_do, "do");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_double = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_double, "double");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_else = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_else, "else");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_extends = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_extends, "extends");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_false = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_false, "false");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_final = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_final, "final");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_finally = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_finally, "finally");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_float = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_float, "float");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_for = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_for, "for");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_goto = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_goto, "goto");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_if = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_if, "if");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_implements = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_implements, "implements");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_import = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_import, "import");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_instanceof = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_instanceof, "instanceof");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_int = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_int, "int");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_interface = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_interface, "interface");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_long = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_long, "long");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_native = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_native, "native");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_new = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_new, "new");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_null = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_null, "null");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_package = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_package, "package");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_private = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_private, "private");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_protected = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_protected, "protected");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_public = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_public, "public");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_return = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_return, "return");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_short = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_short, "short");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_static = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_static, "static");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_strictfp = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_strictfp, "strictfp");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_super = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_super, "super");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_switch = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_switch, "switch");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_synchronized = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_synchronized, "synchronized");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_this = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_this, "this");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_throw = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_throw, "throw");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_throws = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_throws, "throws");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_transient = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_transient, "transient");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_true = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_true, "true");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_try = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_try, "try");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_void = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_void, "void");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_volatile = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_volatile, "volatile");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LITERAL_while = new at.dms.compiler.tools.antlr.extra.CToken(LITERAL_while, "while");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(ASSIGN, "=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BAND = new at.dms.compiler.tools.antlr.extra.CToken(BAND, "&");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BAND_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(BAND_ASSIGN, "&=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BNOT = new at.dms.compiler.tools.antlr.extra.CToken(BNOT, "~");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BOR = new at.dms.compiler.tools.antlr.extra.CToken(BOR, "|");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BOR_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(BOR_ASSIGN, "|=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BSR = new at.dms.compiler.tools.antlr.extra.CToken(BSR, ">>>");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BSR_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(BSR_ASSIGN, ">>>=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BXOR = new at.dms.compiler.tools.antlr.extra.CToken(BXOR, "^");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_BXOR_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(BXOR_ASSIGN, "^=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_COLON = new at.dms.compiler.tools.antlr.extra.CToken(COLON, ":");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_COMMA = new at.dms.compiler.tools.antlr.extra.CToken(COMMA, ",");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_DEC = new at.dms.compiler.tools.antlr.extra.CToken(DEC, "--");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_DOT = new at.dms.compiler.tools.antlr.extra.CToken(DOT, ".");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_EQUAL = new at.dms.compiler.tools.antlr.extra.CToken(EQUAL, "==");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_GE = new at.dms.compiler.tools.antlr.extra.CToken(GE, ">=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_GT = new at.dms.compiler.tools.antlr.extra.CToken(GT, ">");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_INC = new at.dms.compiler.tools.antlr.extra.CToken(INC, "++");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LAND = new at.dms.compiler.tools.antlr.extra.CToken(LAND, "&&");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LBRACK = new at.dms.compiler.tools.antlr.extra.CToken(LBRACK, "[");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LCURLY = new at.dms.compiler.tools.antlr.extra.CToken(LCURLY, "{");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LE = new at.dms.compiler.tools.antlr.extra.CToken(LE, "<=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LNOT = new at.dms.compiler.tools.antlr.extra.CToken(LNOT, "!");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LOR = new at.dms.compiler.tools.antlr.extra.CToken(LOR, "||");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LPAREN = new at.dms.compiler.tools.antlr.extra.CToken(LPAREN, "(");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_LT = new at.dms.compiler.tools.antlr.extra.CToken(LT, "<");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_MINUS = new at.dms.compiler.tools.antlr.extra.CToken(MINUS, "-");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_MINUS_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(MINUS_ASSIGN, "-=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_NOT_EQUAL = new at.dms.compiler.tools.antlr.extra.CToken(NOT_EQUAL, "!=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_PERCENT = new at.dms.compiler.tools.antlr.extra.CToken(PERCENT, "%");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_PERCENT_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(PERCENT_ASSIGN, "%=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_PLUS = new at.dms.compiler.tools.antlr.extra.CToken(PLUS, "+");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_PLUS_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(PLUS_ASSIGN, "+=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_QUESTION = new at.dms.compiler.tools.antlr.extra.CToken(QUESTION, "?");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_RBRACK = new at.dms.compiler.tools.antlr.extra.CToken(RBRACK, "]");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_RCURLY = new at.dms.compiler.tools.antlr.extra.CToken(RCURLY, "}");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_RPAREN = new at.dms.compiler.tools.antlr.extra.CToken(RPAREN, ")");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SEMI = new at.dms.compiler.tools.antlr.extra.CToken(SEMI, ";");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SL = new at.dms.compiler.tools.antlr.extra.CToken(SL, "<<");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SLASH = new at.dms.compiler.tools.antlr.extra.CToken(SLASH, "/");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SLASH_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(SLASH_ASSIGN, "/=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SL_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(SL_ASSIGN, "<<=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SR = new at.dms.compiler.tools.antlr.extra.CToken(SR, ">>");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_SR_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(SR_ASSIGN, ">>=");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_STAR = new at.dms.compiler.tools.antlr.extra.CToken(STAR, "*");
  at.dms.compiler.tools.antlr.extra.CToken	TOKEN_STAR_ASSIGN = new at.dms.compiler.tools.antlr.extra.CToken(STAR_ASSIGN, "*=");
}
