# only good for gathering graph-level statistics at this point (see README)
all:
	strc -nodatacollapse -stats SampleTrellis.str CharPrinter.str DataSource.str DownSample.str ExampleSource.str FrameMaker.str IntPrinter.str NoiseSource.str RateDoubler.str Shifter.str TrellisDecoder.str TrellisEncoder.str UnFrameMaker.str UnShifter.str
