#!/usr/local/bin/bash

#options:
#input directory -i
#output file -o

extract_concat() {
    #extract info from file name
    local current 
    local OLDIFS

    current="$indir/$1"
    
    if [ -f $current ]; then
	echo -n ${1%%-*} >> $outfile
	echo -n ";\"-"${1#*-}"\";" >> $outfile
    fi

    #extract results from file
    echo -n $(tail -1 $current) >> $outfile
    
    echo >> $outfile
}

while getopts ":i:o:" opt; do
	case $opt in
	i  ) indir=$OPTARG;;
	o  ) outfile=$OPTARG;;
	\? ) echo 'usage: condense -i input_dir -o output_file'
	     exit 1;;
	esac
done

if [ -z "$indir" ] || [ -z "$outfile" ]; then
    echo 'usage: condense -i input_dir -o output_file'
    exit 1
fi

rm -f $outfile
#echo "Benchmark;Options;Tiles in Config;Tiles Assigned;Cycles per Steady;Outputs Per Steady;Thruput per 10^5;MFLOPS;instr issued;FPU;MEM;Branch;Admin;ALU;max instr issued" >> $outfile

print_header="1"

#concat all the files
files=$(ls $indir)
for file in $files; do
    #extract the info and write to the output file
    if [ -f "$indir/$file" ]; then
	if [ $print_header = "1" ]; then
	    echo -n "benchmark;options;" >> $outfile
	    echo $(tail -2 "$indir/$file" | grep "tiles") >> $outfile
	    print_header="0"
	fi
	extract_concat $file
    fi
done

