#!/bin/sh
#
# get-antlr: download an antlr.jar from the ANTLR Web site
# needs periodic updating to point to a version that is still
# kept at antlr.org.
#
test -f $1 && exit 0
wget http://www.antlr.org/download/antlr-2.7.6.tar.gz
gunzip antlr-2.7.6.tar.gz
tar xf antlr-2.7.6.tar antlr-2.7.6/antlr.jar
mv antlr-2.7.6/antlr.jar $1
rm -rf antlr-2.7.6 antlr-2.7.6.tar
