# Makefile.vars: Autoconf-detected program locations

# AUTOCONFISCATE VAR = @VAR@
CC = gcc
CXX = g++
JAVA = java
JAVAC = jikes
JIKES = jikes
LATEX = latex
BIBTEX = bibtex
DVIPS = dvips
MPOST = mpost
PS2PDF = ps2pdf
HEVEA = hevea
IMAGEN = imagen
PERL = perl
# END AUTOCONFISCATE
