#!/bin/sh
#PBS -l nodes=1:dual2.2GHz
#PBS -k n
#PBS -m n
#PBS -q long
#PBS -v STREAMIT_HOME=/u/dmaze/src/streams
#PBS -N streamitall
#PBS -S /bin/sh

# Run the "all" regression tests under OpenPBS.  Submit this script
# using 'qsub', possibly via cron.

$STREAMIT_HOME/regtest/tools/run_reg_tests.pl
