#!/bin/sh
#PBS -l nodes=1:dual2.2GHz
#PBS -o /dev/null
#PBS -e /dev/null
#PBS -m n
#PBS -M nobody@cag.lcs.mit.edu
#PBS -q unbound
#PBS -v STREAMIT_HOME=/u/dmaze/src/streams
#PBS -N streamitall
#PBS -S /bin/sh

# Run the "all" regression tests under OpenPBS.  Submit this script
# using 'qsub', possibly via cron.

$STREAMIT_HOME/regtest/tools/run_reg_tests.pl
