// Generated by msggen from IncludeMessages.msg
package at.dms.compiler.tools.include;

import at.dms.compiler.tools.common.MessageDescription;

public interface IncludeMessages extends at.dms.compiler.tools.common.CompilerMessages {
  MessageDescription	CANNOT_OPEN_FILE = new MessageDescription("Cannot open file \"{0}\": {1}", "INCLUDE", 0);
}
