#!/bin/sh
#PBS -N streamit_nightly
#PBS -S /bin/sh
#PBS -q unbound@cagfarm-01
#PBS -l nodes=1:fast:rhel3:ppn=2
#PBS -o /dev/null
#PBS -e /dev/null
#PBS -m a
#PBS -M dimock@csail.mit.edu
#PBS -q unbound
#PBS -v STREAMIT_HOME="/home/bits7/dimock/streams",PERL5LIB="/usr/uns/encap/perl-5.8.0/lib/5.8.0:/u/dimock/lib/site_perl/5.8.0"

# Run the "nightly" regression tests under OpenPBS.  Submit this script
# using 'qsub', possibly via cron.
umask 002
alias gcc='gcc34'
alias g++='gcc34'
export CC=gcc34
export CXX=gcc34
$STREAMIT_HOME/regtest/qmtest/run-reg-tests.py nightly
