#!/bin/sh
#
# streamitqm: Prepare the StreamIt tree for QMTest
# David Maze <dmaze@cag.lcs.mit.edu>
# $Id: streamitqm,v 1.5 2007-04-03 23:45:08 dimock Exp $
#
# the $PYTHON variable can be used to override the #! specification in
# build-qmtest.py
#
# (This script is no longer called from run-reg-tests.py)
#

cd "$STREAMIT_HOME"
FILES="classes.qmc configuration streamit.py"

case "$1" in
    setup)
	test -d QMTest || mkdir QMTest
	for f in $FILES; do cp ./regtest/qmtest/$f QMTest; done
	if [ -z "$2" ]; then
	  $PYTHON  ./regtest/qmtest/build-qmtest.py ./regtest/qmtest/regtest.xml
        else
	    shift
          $PYTHON  ./regtest/qmtest/build-qmtest.py "$@"
        fi
	;;

    clean)
	rm -rf QMTest apps.qms results.qmr
	;;

#     commit)
# 	cp QMTest/* regtest/qmtest
# 	;;

    *)
#	echo "Usage: streamitqm [setup|clean|commit]" >&2
	echo "Usage: streamitqm [setup|clean]" >&2
	exit 1
	;;
esac
