// Generated by msggen from LexgenMessages.msg
package at.dms.compiler.tools.lexgen;

import at.dms.util.MessageDescription;

public interface LexgenMessages extends at.dms.compiler.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Token \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", "LEXGEN", 0);
}
