// Generated by msggen from BackendMessages.msg
package at.dms.backend;

import at.dms.util.MessageDescription;

public interface BackendMessages extends at.dms.compiler.CompilerMessages {
  MessageDescription	SEMANTIC_ERROR = new MessageDescription("Semantic error found on file \"{0}\": {1}", "OPTIMIZE", 0);
}
